### ISSUE TITLE
[Docs]: Add - Embedded PostgreSQL

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

NA

### Release Number

Na

### First Draft

https://github.com/appsmithorg/appsmith-docs/pull/1000

### Discord/slack/intercom Link if needed

https://theappsmith.slack.com/archives/C02MUD8DNUR/p1678788880121449

### Use cases or user requests

To add docs for Embedded PostgreSQL.

**Comment by jnikhila** [comment]
As [discussed],(https://theappsmith.slack.com/archives/C03C1PPUHDW/p1679055907118739) this will be picked up later.

**Comment by jnikhila** [comment]
@danciaclara - I'll be closing this ticket, and we can add a new ticket to the board when the feature is ready to be documented. CC: @sum35h and @sharat87

**Comment by jnikhila** [comment]
@sharat87 - Could you please confirm if this is not a priority and we can close this ticket?

**Comment by sharat87** [comment]
@jnikhila, yes, let's close this. Not something we want to document right now.
