### ISSUE TITLE
[Docs]: Search modal in doc is not responsive

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#1047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

Search modal appears really small in bigger monitors and is difficult for users to find information. 

https://theappsmith.slack.com/archives/C03C1PPUHDW/p1679576426381149

**Comment by GreenFlux** [comment]
@danciaclara @jnikhila can we also pin the `show all X results` to the top or bottom of the modal? Currently it's hidden at the bottom of the scroll, and there's no obvious way to view the search results in full screen. Users won't even see the link to view the full page results unless the scroll past all the search results.
