### ISSUE TITLE
[Docs]: Add the information about mongo v5 and possible solution

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith-docs#1053]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Discord/slack/intercom Link

https://community.appsmith.com/t/illegal-instruction-core-dumped-mongod-fork-port-27017-dbpath-mongo-db-path/2197

### Describe the problem and improvement.

With v1.9.2 we introduced mongo v5. A handful of instances cannot run said version due to hardware limitations. We should address this in our official docs somewhere. For now, I've created a post on our forum that we'll continue to share with users.

**Comment by jnikhila** [comment]
@pranavkanade - There is a callout added on the [Custom MongoDB & Redis](https://docs.appsmith.com/getting-started/setup/instance-configuration/custom-mongodb-redis) page which provides instruction to upgrade the Replicate Set. 
In the community post, we are talking more about the supported platforms and ways if users don't have the infrastructure setup and would have to use the older version of Appsmith. IMO - we should merge this information. Your thoughts? CC: @danciaclara

**Comment by jnikhila** [comment]
Rehaul the doc page.
