### ISSUE TITLE
[Docs]: App Navigation v1

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith-docs#1075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/pull/19312

### Release Date

3 April 2023

### Release Number

NA

### Loom video

Video here in the PR - https://github.com/appsmithorg/appsmith/pull/19312

### Test plan/cases

https://www.notion.so/appsmith/Test-Plan-a7883ae4980d470690de5c62a41dd168

**Comment by somangshu** [comment]
@jnikhila @danciaclara can we close this task

**Comment by somangshu** [comment]
@jnikhila @danciaclara can we close this task
