### ISSUE TITLE
[Docs]: Air Gapped Edition

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#1113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/12200

### Release Date

27/04/23

### Release Number

v1.9.18

### First Draft

https://www.notion.so/appsmith/Airgap-Documentation-First-Draft-50c6dbbf06664c029ce79093138804bf

### PRD

https://www.notion.so/appsmith/Air-Gapping-Appsmith-98805d25188f4a1281b53104c5b6a72c

**Comment by abhvsn** [comment]
Installation guide: https://www.notion.so/appsmith/Install-Appsmith-in-an-Airgapped-environment-68d35a15e2344c01a661647d00b1c9ed

**Comment by Pranay105** [comment]
Review comments are already shared by @jnikhila on the notion doc. @abhvsn is going to look into it. No action required from the doc team as of now.
