### ISSUE TITLE
[Docs]: Google sheets docs shows new flow

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/datasources/querying-google-sheets

### Describe the problem and improvement.

The new Google sheets flow was added to the docs during rehaul, but this feature is not yet available to users. We need to check the flow on a non-Appsmith account and update this page accordingly

**Comment by spark-c** [comment]
[PR ready](https://github.com/appsmithorg/appsmith-docs/compare/fix/gsheets-revert-scopes?expand=1)
