### ISSUE TITLE
Update backup util appsmithctl docs with new changes

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith-docs#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/pull/22229

### Release Date

15/4/2023

### Release Number

v1.9.14

### Use cases or user requests

Going forward the util cmd `appsmithctl backup` does not stop the backend and rts processes. Essentially there will be no down time when running a manual backup on an Appsmith instance.
It will be the responsibility of the Admin to make sure that a manual backup is really a desired snapshot when done via
the appsmithctl backup util command
To ensure this, Admins may require to stop the `backend` and `rts` processes in the container before a manual backup.

**Comment by jnikhila** [comment]
Done.
