### ISSUE TITLE
[Docs]: Amazon S3 Rehaul

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith-docs#1164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/datasources/querying-amazon-s3

### Describe the problem and improvement.

Rehaul project

**Comment by danciaclara** [comment]
Fixed by https://github.com/appsmithorg/appsmith-docs/pull/1190
