### ISSUE TITLE
[Docs]: Update set up docs with information for timeout and error page

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C02MUD8DNUR/p1682063427032999

### Describe the problem and improvement.

@sum35h - Please add more information if needed.

**Comment by sum35h** [comment]
I don't think specifying the timeout value for the loading page would be necessary, but we can mention at the max time for starting would be 3minutes.

**Comment by jnikhila** [comment]
@sum35h - For Docker, we will add the following:
`Open [https://localhost](https://localhost) and wait for the server to come up. This can take up to 5 minutes. Once the server is up and running, you can access Appsmith at [https://localhost](https://localhost).`

However, for Kubernetes, as we can't access it on localhost, how can a user access the Appsmith?
