### ISSUE TITLE
[Docs]: Upgrade to Business Edition - Kubernetes

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1208]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/upgrade-to-business-edition/kubernetes

### Describe the problem and improvement.

Rehaul the doc

**Comment by danciaclara** [comment]
fixed by https://github.com/appsmithorg/appsmith-docs/pull/1324
