### ISSUE TITLE
[Docs]: Improving the sentence in the docs.

### ISSUE THREAD

**Issue by ayushkumarbhadani** [appsmithorg/appsmith-docs#1216]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Documentation Link

https://github.com/appsmithorg/appsmith/blob/master/contributions/CodeContributionsGuidelines.md

### Describe the problem and improvement.

Sentence in the documentation: This is very important step as it `the` registers the regex to be scanned by the git-secrets.

`the` should be removed from the sentence :)

**Comment by danciaclara** [comment]
@somangshu Please take this ahead and assign it to somebody who can pick this up.

**Comment by ayushkumarbhadani** [comment]
I can do this!
