### ISSUE TITLE
[Docs]: Widget Landing Page - Rehaul

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#1229]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets

### Describe the problem and improvement.

Widget Landing Page Rehaul

**Comment by danciaclara** [comment]
completed via https://github.com/appsmithorg/appsmith-docs/pull/1228
