### ISSUE TITLE
[Docs]: Clarify the schedule in auto update Appsmith

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#1320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-management/update-appsmith#automatic-update

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1685456084561999

### Describe the problem and improvement.

We need to clarify that the cron job is set to check for updates at so and so time by default. Else users expect the update to start automatically after they set it up

**Comment by jnikhila** [comment]
Closed as part of #1321
