### ISSUE TITLE
[Task]: Add GitHub action for Algolia index updates to prevent search from breaking

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#1402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

-

### Release Date

-

### Release Number

-

### Use cases or user requests

Add a Github action to wait when an index update is already in progress.Else this breaks the search on documentation.

**Comment by danciaclara** [comment]
@jnikhila this broke again on Friday.

**Comment by jnikhila** [comment]
@danciaclara - As the index update is scheduled, and is working as expected. I think we can close this issue.
