### ISSUE TITLE
[Docs]: Rehaul - Query object

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#1419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/appsmith-framework/query-object

### Describe the problem and improvement.

Rehaul the content and if required, restructure the page

**Comment by danciaclara** [comment]
closed via https://github.com/appsmithorg/appsmith-docs/pull/1461
