### ISSUE TITLE
[Docs]: Gmail Email Configuration

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1421]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-configuration/email/gmail

### Describe the problem and improvement.

Rehaul the doc.

**Comment by danciaclara** [comment]
closed via https://github.com/appsmithorg/appsmith-docs/pull/1446
