### ISSUE TITLE
[Docs]: Rehaul Prepared Statements

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith-docs#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/connect-data/concepts/how-to-use-prepared-statements

### Describe the problem and improvement.

Rehaul of concepts page for Prepared Statements in the Connect Data > Concepts section.

**Comment by danciaclara** [comment]
closed via https://github.com/appsmithorg/appsmith-docs/pull/1466
