### ISSUE TITLE
[Task]: Check if we can implement dynamic updates in commands or code

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#1442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C01CFTXD0N8/p1688374112166369

### Describe the problem and improvement.

Check if Docusaurus allows us to dynamically shows the commands and code based on user input/data.

**Comment by jnikhila** [comment]
@Nikhil-Nandagopal - Could you please confirm the priority or if we need to invest time in this?

**Comment by Nikhil-Nandagopal** [comment]
No let's not worry about this now
