### ISSUE TITLE
[Docs]: Add docs for `appsmith.theme` object

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#1459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

Adding docs for `appsmith.theme` object

**Comment by dilippitchika** [comment]
# Appsmith theme object

Appsmith theme object contains the details of the theme properties applied to the application. We can use the properties from this object to 

1. Set certain properties in widgets to be aligned with theme. For example, setting the font family of text widget to refer to the theme’s font family.
2. Write custom logic like to suggest a font color based on the theme’s primary color.

Appsmith theme has the following properties which are accessible for your reference

1. `colors`:
    1. `primaryColor` - It refers to the background color set in the theme section of app settings
    2. `backgroundColor` - It refers to the background color set in the theme section of app settings
2. `borderRadius`
    1. `appBorderRadius` - It refers to the border radius set in the theme section of app settings
3. `boxShadow`
    1. `appBoxShadow` - It refers to the border radius set in the theme section of app settings
4. `fontFamily`
    1. `appFont` - It refers to the font family set for the app in the theme section for app settings
