### ISSUE TITLE
[Docs]: Add docs for missing User object attributes

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#1460]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/appsmith-framework/context-object#user-object

### Describe the problem and improvement.

Currently we are only explaining 2-3 attributes of the user object in the docs. Each user object property should be covered.

**Comment by jnikhila** [comment]
@bharath31 - As this is a reference change, could you please review and raise a PR for this?
