### ISSUE TITLE
[Docs]: CDN Setup instructions

### ISSUE THREAD

**Issue by SatishGandham** [appsmithorg/appsmith-docs#1477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/25424

### Release Date

TBD

### Release Number

NA

### First Draft

https://www.notion.so/appsmith/Appsmith-CloudFront-CDN-9b8563aa8b794695976516edee2431e8

### PRD

https://www.notion.so/appsmith/CDN-for-static-resources-01e82d4b2f914f3ba489616a9f3310bd#b4dbcb5aa90b4d6098412226535da055

### Use cases or user requests

There are two ways to setup CDN. We should have docs for both setups showing pros and cons.
https://www.notion.so/appsmith/CDN-for-static-resources-01e82d4b2f914f3ba489616a9f3310bd#b4dbcb5aa90b4d6098412226535da055

Should be published after successful completion of https://github.com/appsmithorg/appsmith/issues/25424

**Comment by jnikhila** [comment]
@SatishGandham - Is this an internal documentation? CC: @sum35h

**Comment by jnikhila** [comment]
@somangshu - Do you have any insights on this?

**Comment by somangshu** [comment]
@Nikhil-Nandagopal this will be required after https://github.com/appsmithorg/appsmith/issues/25424 is completed.

**Comment by jnikhila** [comment]
@somangshu - According to @sum35h this doc will be internal documentation. But as confirmed by you it will eventually be added to the documentation. Do you have a tentative release date for the engineering ticket? It will help us prioritise it for work.

**Comment by somangshu** [comment]
Not right now @jnikhila, we might be able to allocate bandwidth to this mid of this month, ill keep you posted accordingly!

**Comment by danciaclara** [comment]
@somangshu any update on this?

**Comment by jnikhila** [comment]
@sum35h - could you please confirm this comment? https://github.com/appsmithorg/appsmith-docs/issues/1477#issuecomment-1643392130

**Comment by somangshu** [comment]
cc @sharat87

**Comment by sum35h** [comment]
I believe there will be more changes to the CDN in the future, but as of today the steps to setup the CDN are documented internally [here](https://www.notion.so/appsmith/Appsmith-CDN-CloudFront-926cb3473c0f4c37ab6f39f32631088c?pvs=4).

**Comment by jnikhila** [comment]
@somangshu - Do you have any insights on the [ticket](https://github.com/appsmithorg/appsmith/issues/25424) priority?

**Comment by somangshu** [comment]
@jnikhila ill discuss this with the perf team and get back here.

**Comment by jnikhila** [comment]
@somangshu and @rajatagrawal - Could you please validate and do the needful? If not needed or deprioritised, please add comments and close the ticket.

**Comment by rajatagrawal** [comment]
I think we can close this ticket for now. Will reopen it if it is needed again.
