### ISSUE TITLE
[Docs]: Wrong env var for embedded postgres

### ISSUE THREAD

**Issue by pranavkanade** [appsmithorg/appsmith-docs#1487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/installation-guides/aws-ecs-on-fargate#create-task-and-container-definitions

### Discord/slack/intercom Link

https://app.frontapp.com/inboxes/teams/views/198513292/archived/81297344908

### Describe the problem and improvement.

ENV key to enable/disable embedded Postgres is `APPSMITH_EMBEDDED_DB` instead of `APPSMITH_ENABLE_EMBEDDED_DB`

**Comment by jnikhila** [comment]
@pranavkanade - the correct environment variable `APPSMITH_ENABLE_EMBEDDED_DB` is already available in the ECS Fargate doc. Please refer to the screenshot below:
![Screenshot 2023-07-19 at 3.11.53 PM.png](https://images.zenhubusercontent.com/6203759d49a2167250e9a805/5450482c-0905-4bff-b905-87e5cf661f06)

Please verify.

**Comment by jnikhila** [comment]
@sum35h - Could you please confirm which environment variable should be added and the description?

**Comment by sum35h** [comment]
The correct ENV key is `APPSMITH_ENABLE_EMBEDDED_DB`.
Closing this since it's already out.
