### ISSUE TITLE
[Docs]: Security 

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/product/security

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C03C1PPUHDW/p1689767536464499

### Describe the problem and improvement.

The security doc is outdated. Update the parts or the whole doc as needed.

**Comment by spark-c** [comment]
[Notion](https://www.notion.so/appsmith/Security-1f38e99f37374f5388d1d13893f78a9a)
