### ISSUE TITLE
[Docs]: Update select and multi select widget docs

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith-docs#1513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/select
http://localhost:3000/reference/widgets/multiselect

### Describe the problem and improvement.

As part of https://github.com/appsmithorg/appsmith/issues/24022, we have updated the properties of the Select and Multi-select widgets.

We have now introduced two new properties (label and value) and modified how an existing property (options) works.

Changes to the documents is available on the following PR - 
https://github.com/appsmithorg/appsmith-docs/pull/1512

**Comment by sbalaji1192** [comment]
CC @dilippitchika

**Comment by jnikhila** [comment]
@Pranay105 and @harshilp24 - Could you please look into these changes, and merge it to the Rehaul changes for select and multi select?

**Comment by harshilp24** [comment]
@Pranay105 are you incorporating these changes as part of the rehaul PRs? or should I take this up?
