### ISSUE TITLE
[Docs]: API documentation for SCIM endpoints

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#1520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/20404

### Release Date

03/08/23 (This doc is not required at release)

### Release Number

v1.9.21

### PRD

https://www.notion.so/appsmith/User-Lifecycle-Management-e1f718e2e34341919d006f20d8cb5deb

### Use cases or user requests

Apart from integrating with IdPs, SCIM endpoints can be used to automate user lifecycle management. Customers can write automation to call the endpoint when they want to add, remove users, or sync groups. Documenting the API will allows customers to access our endpoints.

Liks this example - [Postman SCIM](https://www.postman.com/postman/workspace/scim/documentation/6248949-de4a96e2-9ebf-426f-bc55-4c5f2de51ab2)

This doesn't need to be done on release, can be done in the few weeks after release as well.

**Comment by jnikhila** [comment]
@infinitetrooper - Could you please confirm when can you share the first draft for this ticket?

**Comment by infinitetrooper** [comment]
@jnikhila - Let's put a pause on this for the time being. It's not a priority and I would need to find some bandwidth to get this done. Let me ping you once I have the documentation with me.

**Comment by jnikhila** [comment]
Thanks @infinitetrooper. I'll close this ticket. Let's open a new ticket when we are ready to work on this. CC: @danciaclara
