### ISSUE TITLE
[Docs]: Rehaul - Code Scanner

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#1538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/code-scanner

### Describe the problem and improvement.

Update the structure, rehaul the content

**Comment by danciaclara** [comment]
closed via https://github.com/appsmithorg/appsmith-docs/issues/1538
