### ISSUE TITLE
[Docs]: Custom server timeout ENV configuration

### ISSUE THREAD

**Issue by sum35h** [appsmithorg/appsmith-docs#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/14535

### Release Date

8/06/23

### Release Number

1.9.26

### Draft

The internal Appsmith server timeout is st to 60s by default. In case you are running queries taking longer than 60s, the env var APPSMITH_SERVER_TIMEOUT will also need to be set to a value greater than 60 apart from updating the query timeout in the query settings of Appsmith.

**note: **The value of the timeout is in seconds and does not need to be specified, so if you need a timeout of 80seconds it should be:
`APPSMITH_SERVER_TIMEOUT=80`

**Comment by jnikhila** [comment]
This will be fixed as part of #1447

**Comment by danciaclara** [comment]
this info will need to be mentioned or called out in these pages as well
https://docs.appsmith.com/help-and-support/troubleshooting-guide/action-errors#timeout-error
https://docs.appsmith.com/core-concepts/data-access-and-binding/querying-a-database#run-a-query
https://docs.appsmith.com/connect-data/reference/query-settings
