### ISSUE TITLE
Add Appsmith Shortcuts Page

### ISSUE THREAD

**Issue by vihar** [appsmithorg/appsmith-docs#160]

**Comment by vihar** [comment]
There is no information about shortcuts on documentation, this can be viewed on an application using the `Command/Control + ?` on editor mode. 

<img width="1082" alt="CleanShot 2022-02-22 at 15 43 15@2x" src="https://user-images.githubusercontent.com/16307796/155111158-506233f1-30e5-40a6-a17f-9de127f6957f.png">

**Comment by danciaclara** [comment]
@jnikhila This is completed right? https://docs.appsmith.com/advanced-concepts/more/keyboard-shortcuts

**Comment by jnikhila** [comment]
Yes @danciaclara.
