### ISSUE TITLE
[Docs]: custom environments feature

### ISSUE THREAD

**Issue by ayushpahwa** [appsmithorg/appsmith-docs#1674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/25879

### Release Date

28/09/2023

### Release Number

v1.9.38/v1.9.39

### Loom video

[Video](https://drive.google.com/file/d/14fzJAouyjXkMv7PxoE8njqE6rxKAeenv/view?usp=sharing)

**Comment by danciaclara** [comment]
@ayushpahwa assigning it to you for first draft

**Comment by ayushpahwa** [comment]
Added link to the video
