### ISSUE TITLE
[Docs]: Broken link in the Contribution Guide

### ISSUE THREAD

**Issue by narhzih** [appsmithorg/appsmith-docs#1689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/GlobalFunctions.md

### Discord/slack/intercom Link

https://app.frontapp.com/open/cnv_122k3lcc?key=x9JcoLKeUJKK8KnN6vuzr82AL6RKQzRc

### Describe the problem and improvement.

There's link in the Global Functions documentation that doesn't work. Whenever this link is clicked, it takes me to a page that says "404" not found. It would be helpful is this link is updated. 

Here's a link to the file - https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/editorComponents/ActionCreator/Fields.tsx

**Comment by jnikhila** [comment]
@somangshu - Could you please help here? Also, as per our previous conversation, I was referring to these types of doc issues where it's related to engineering modifying the docs.

**Comment by somangshu** [comment]
@appsmithorg/fe-coders-pod need help here. This doc was last altered by a dev in FE team. 

cc @satbir121

**Comment by somangshu** [comment]
[this](https://github.com/appsmithorg/appsmith/pull/13969) is the PR where the change was made

**Comment by jnikhila** [comment]
@somangshu - The PR linked is merged. I'm closing the ticket. Please feel free to reopen if that's not the case.
