### ISSUE TITLE
[Docs]: Add documentation for Custom ECharts in Chart Widget

### ISSUE THREAD

**Issue by rajatagrawal** [appsmithorg/appsmith-docs#1690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/24424

### Release Date

Feature merged behind feature flag. ETA : September 15th.

### Release Number

NA

### First Draft
https://www.notion.so/appsmith/Custom-ECharts-Documentation-Draft-2232f6ccedf04f68af51c0b2ddf1afbb?pvs=4

**Comment by danciaclara** [comment]
@rajatagrawal when will this be available for all users?

**Comment by rajatagrawal** [comment]
@danciaclara 

This feature has been merged to release 2 weeks ago behind a feature flag. We are working on some bug fixes for it before making it live. The bugs should be solved by end of September. The feature can be made live after that.
