### ISSUE TITLE
[Docs]: Dynamic Bindings support within Datasources

### ISSUE THREAD

**Issue by riteshkew** [appsmithorg/appsmith-docs#1696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C0341RERY4R/p1694426840975269

### Describe the problem and improvement.

There seems to be confusion among users around the usage of dynamic bindings within datasource configuration. Due to an earlier implementation gap, users were able to use bindings within datasource configs, but with multiple environments infra changes, we fixed the gap and now it is not supported. We need to update our docs to clearly mention where bindings are supported and where they are not.

**Comment by danciaclara** [comment]
@sondermanish Could you give us a rough draft about what is possible and what is not with an explanation, so that we can pick this up on high priority?

**Comment by jnikhila** [comment]
@riteshkew - We are awaiting information from Manish.

**Comment by danciaclara** [comment]
First draft - https://www.notion.so/appsmith/Dynamic-Binding-Scope-225043f20abf4ad1972fd57db20d8a98?pvs=4

**Comment by rashmi-sahoo-git** [comment]
PR preview link - https://appsmith-docs-git-1696-dynamicbinding-suppo-4dfb33-get-appsmith.vercel.app/connect-data/concepts
