### ISSUE TITLE
[Docs]: Update Feedback Widget

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

NA

### Describe the problem and improvement.

Update the feedback widget as per design guidelines.

**Comment by vasanthappsmith** [comment]
[Figma](https://www.figma.com/file/Yc4kKCiCeaTSL9VjWEG021/docs?type=design&node-id=12-916&mode=design&t=xwSEwpmEzd1vNO2T-4)

![image](https://github.com/appsmithorg/appsmith-docs/assets/92305123/9dce55ea-b02a-45aa-bbdd-41b189b97b1e)
![image](https://github.com/appsmithorg/appsmith-docs/assets/92305123/7b98c0e9-b059-42cd-bfb4-002922e65c40)
d

**Comment by jnikhila** [comment]
@Nikhil-Nandagopal and @danciaclara - Above are the design suggestions shared by @vasanthappsmith.
As per @vasanthappsmith - the more appropriate position to place the feedback widget will be in the footer. This will ensure that its position is fixed. However, in TOC, the position of the feedback widget moves based on the content rendered. 

There are other suggestions like sidebar background, selected content, and hover actions for multiple components. Do we need to make all these changes as part of the design improvements for the feedback widget? Please confirm.
