### ISSUE TITLE
[Docs]: Git Connect UX update

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#1702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/25588

### Release Date

18/09/2023 (it is under feature flag so, full release will happen by 30/09/2023)

### Release Number

v1.9.38

### First Draft

https://www.figma.com/file/U6LxjAfca1BB5sje1HsatX/Git-connect-and-import?type=design&node-id=3419-35&mode=design&t=mpNXWUIF1lhGm5Bd-0

### Use cases or user requests

This is purely a change in UI which makes the process self-explanatory. Only a small section of the [Connect Git Repository](https://docs.appsmith.com/advanced-concepts/version-control-with-git/connecting-to-git-repository?version-control=azure) page needs to be updated.

**Comment by danciaclara** [comment]
@infinitetrooper Its difficult to understand what exactly is the change that needs to be done by looking at the Figma file. If its a small change in screenshot, you can go ahead and raise the PR and we can publish it

**Comment by danciaclara** [comment]
closed by https://github.com/appsmithorg/appsmith-docs/pull/1761
