### ISSUE TITLE
[Docs]: Update the callout for business edition

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

- Update the callouts as per current plans available on the website.
- Update the terminology to use plan(s).

**Comment by vasanthappsmith** [comment]
@jnikhila Here it is [Figma](https://www.figma.com/file/Yc4kKCiCeaTSL9VjWEG021/docs?type=design&node-id=20-1060&mode=design&t=UY1iU9RU9dK6lPH0-4)

**Comment by jnikhila** [comment]
The changes for this ticket will fix #1711.

**Comment by jnikhila** [comment]
Instead of updating callouts, we'll add appropriate tags. The tags will be added as per the [pricing](https://www.appsmith.com/pricing) page.
