### ISSUE TITLE
[Docs]: Update the notice design

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#1728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

NA

### Release Number

NA

### First Draft

NA

### Use cases or user requests

Update the design for notices. Something similar to https://developers.google.com/style/notices#examples

**Comment by jnikhila** [comment]
@vasanthappsmith - Could you please add this to the design pipeline, once the designs are ready please pass it on to the doc team.

**Comment by vasanthappsmith** [comment]
Here it is [Figma](https://www.figma.com/file/Yc4kKCiCeaTSL9VjWEG021/docs?type=design&node-id=90-1172&mode=design&t=3ggmnx9BVTBtyuLe-4)

**Comment by jnikhila** [comment]
@vasanthappsmith - As discussed earlier, here are the [callouts](https://docusaurus.io/docs/next/markdown-features/admonitions) available in Docusaurus. Could you please modify the design for these?

**Comment by jnikhila** [comment]
Closing this. We will revisit if needed.
