### ISSUE TITLE
[Docs]: Using HTTP scheme instead of HTTPS in the Appsmith Community Edition installation guide using Docker 

### ISSUE THREAD

**Issue by zarinfam** [appsmithorg/appsmith-docs#1752]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/installation-guides/docker

### Describe the problem and improvement.

During the installation and run of Appsmith Community Edition locally using Docker, In the last step (3rd), when we want to open the Appsmith in the browser, the link with the HTTPS scheme ([https://localhost](https://localhost)) does not work, and it should be the HTTP scheme ([http://localhost](http://localhost)).
This improvement provides a better experience for those who want to install and run Appsmith Community Edition locally using Docker for the first time.

**Comment by danciaclara** [comment]
closed by https://github.com/appsmithorg/appsmith-docs/pull/1753
