### ISSUE TITLE
[Docs]: Upload Camera Captured Image to S3

### ISSUE THREAD

**Issue by rashmi-sahoo-git** [appsmithorg/appsmith-docs#1756]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/connect-data/how-to-guides/how-to-use-the-camera-image-widget-to-upload-download-images

### Describe the problem and improvement.

- Rename the doc title.
- Move the download section to a separate topic.
- Check the "Upload image using image widget" section and see if this needs to be improvised or removed.

**Comment by jnikhila** [comment]
Fixed as part of #1762 and #1778
