### ISSUE TITLE
[Docs]: Adding Elestio as Deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [appsmithorg/appsmith-docs#1763]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

Hey team,
I have made similar addition to the [appsmith/appsmith](https://github.com/appsmithorg/appsmith/issues/27815) repo and would like to the same here. I will re-add the previous context here.
I am Kaiwalya, Developer Advocate at Elestio. We have a option to fully manage Appsmith on Elestio, the dedicated page for the same can be found [here](https://elest.io/open-source/appsmith). I think it would be a great idea if we can add it as one-click deployment options here.
Additionally, we all collaborate with project by sharing the revenue with them. If it interests you, do let me know :)

**Comment by danciaclara** [comment]
Hi @kaiwalyakoparkar. Thank you for raising the PR.  In the product documentation, we are only adding deployment options that are fully supported by our team in terms of updates, plan upgrades and support. However, this would be a great addition to our community content - https://community.appsmith.com/content. You can create the content and apply for review on the portal.
