### ISSUE TITLE
[Docs]: ECS Installation docs improvements

### ISSUE THREAD

**Issue by sharat87** [appsmithorg/appsmith-docs#1927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/installation-guides/aws-ecs-on-fargate

## ECS Installation Experience

- [ ] Screenshots and UI directions belong to AWS old UI. Many things it asks me to click on, don't even exist.
   - Also needs lots more screenshots, preferably annotated screenshots.

- [ ] There's instructions for configuring both ports 80 and 443 in the Load Balancer configuration, but the UI is only letting me do _one_ port configuration.

- [ ] Typo, "Port 80 Configuration" is repeated. The second occurrence should be "Port 443 configuration".

- [ ] The header "Connect to Fargate instance" gave me the impression that I should read it to access my Fargate Appsmith from a browser. That's not what this section is about.

- [ ] The doc doesn't end with me opening a URL in the browser and seeing Appsmith. I'm left to figure that out myself.

**Comment by sharat87** [comment]
Hey, sorry, missed this.

> What do you think the title could be to make it intuitive for users
I think "Open Terminal into a Fargate instance" is less ambiguous.

> Do you expect the steps should be added to get this info in the doc?
Yes please. There's no explicit expectation of what I'll get by the end of the doc, but the implicit assumption, is that I'll have a running Appsmith that I can open in my browser. But the end of the doc lacks a conclusion that takes me there.

**Comment by jnikhila** [comment]
@shri - The AWS ECS on EC2 and AWS ECS on Farget docs are rehauled and updated for using the new console. Could you please review and close this ticket?
