### ISSUE TITLE
[Docs]: Auto-commit in Git

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#1959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/24793

### Release Date

20/12/23

### Release Number

v1.9.53

### PRD

https://www.notion.so/appsmith/Auto-Committing-Migration-c4d0951431204a77b52826280b4a963f

### Use cases or user requests

We're adding auto-commit to solve the problems of user seeing unmade changes when Appsmith upgrades, we just need to add a section explaining this and how to disable it.

**Comment by danciaclara** [comment]
@infinitetrooper could you share a loom video how this works? Asking cause we want to evaluate whether this needs documentation

**Comment by infinitetrooper** [comment]
It happens in the background so, can't share a Loom video. The gist is this

1. Whenever Appsmith instance upgrades, the DSL version usually upgrades to handle new features on Canvas.
2. This upgrade in the DSL version along with the corresponding changes show up as uncommitted changes for the developer on the app.
3. As the developer did not make these changes explicitly, they are confused and worried about what the changes are
4. So, we're automatically committing these changes to ensure the developer doesn't see them. They will see a commit in their repo as `System generated commit, to support new features after upgrading Appsmith to the version: #appsmithVersion`

We need to communicate that we do this automatically to handle system changes and it won't happen on protected branches and they can choose to disable it in Git settings.
