### ISSUE TITLE
[Docs]: Docs for Sealos

### ISSUE THREAD

**Issue by yangchuansheng** [appsmithorg/appsmith-docs#1967]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://github.com/appsmithorg/appsmith-docs/pull/1832

### Describe the problem and improvement.

I'm interested in making my contribution fully supported by your team. Could you please guide me on what steps need to be taken or criteria that need to be met in order to achieve this? Is there any specific guidelines or best practices that I should follow to align my contribution with your updates, plan upgrades and support?

**Comment by danciaclara** [comment]
Hi @yangchuansheng Thank you for your contribution. In the product documentation, we are only adding deployment options that are fully supported by our team in terms of updates, plan upgrades and support. However, this would be a great addition to our community content - https://community.appsmith.com/content. You can directly create the content and apply for review on the portal.
