### ISSUE TITLE
[Docs]: Continuous Delivery with Git

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#2057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/11522

### Release Date

02/02/2024

### Release Number

v1.9.62

### PRD

https://www.notion.so/appsmith/Solution-Alignment-0d7e1b1f830241d48a02ec08f92601b2?pvs=4#8b0abdd61ace4f179eec4742bb6f9074

### Use cases or user requests

Teams use Git to support multiple environments across instances. The current approach requires pull and deploy leading to manual overhead, unwanted access, and increased surface area for human errors. To solve this, we're building a series of features to automate the build, review & deployment pipeline. Continuous Delivery is an integral part of that feature set.

**Comment by jnikhila** [comment]
https://www.figma.com/file/25VQJtUaJdNK7CuhyxjDy3/Git-CD?type=design&node-id=0-1&mode=design

**Comment by danciaclara** [comment]
@infinitetrooper is this live? We need some more info to be able to document this.

**Comment by jnikhila** [comment]
Merged [#2147](https://github.com/appsmithorg/appsmith-docs/pull/2147)
