### ISSUE TITLE
[Docs]: Authenticated API OAuth in Appsmith

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#2086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C03C1PPUHDW/p1705933144159109

### Describe the problem and improvement.

Users face a lot of issues especially around dealing with access and refresh tokens due to different OAuth flows

**Comment by jnikhila** [comment]
Merged #2160
