### ISSUE TITLE
How to use ArangoDB as a data source on Appsmith

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#210]
Please cover the following topics in this guide -

1. Integrating the datasource into Appsmith.
2. Fetching data from the datasource connected.
3. Binding the data to a widget.
For documentation guidelines, click [here.](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

**Comment by VishalAmbavade** [comment]
Hi! I'm interested in this issue. Can you assign it to me?

**Comment by abhijeet007rocks8** [comment]
Hi @Pranay105, is the issue still open? I would like to work upon the issue.

**Comment by devgossips** [comment]
Hi @Pranay105, is the issue still open? I would like to work upon the issue.
