### ISSUE TITLE
[Docs]: Need to add expires_in field for authenticated API oauth2

### ISSUE THREAD

**Issue by sneha122** [appsmithorg/appsmith-docs#2104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/connect-data/reference/authenticated-api

### Describe the problem and improvement.

In order to solve the issue of [Salesforce not refreshing the token automatically](https://github.com/appsmithorg/appsmith/issues/30239), we have introduced a new field in Authenticated API OAuth2 datasource, where if you select grant type as authentication code, we see a new field appear called expires_in which allows us to customise when we want refresh token flow to be triggered. Attaching video for reference

https://github.com/appsmithorg/appsmith-docs/assets/30018882/721c9f3d-cd4e-4ee0-94b9-e19024c14512

**Comment by danciaclara** [comment]
@sneha122 As its a reference doc, you can directly raise a PR with the changes on this page - https://docs.appsmith.com/connect-data/reference/authenticated-api 
We will review it and merge it when the feature is live. Feel free to reach out in case of any queries.

**Comment by jnikhila** [comment]
Merged #2160
