### ISSUE TITLE
How to use Snowflake as a data source on Appsmith 

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#211]
Please cover the following topics in this guide -

1. Integrating the datasource into Appsmith.
2. Fetching data from the datasource connected.
3. Binding the data to a widget.
For documentation guidelines, click [here.](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

**Comment by VishalAmbavade** [comment]
Hey can you assign me this issue?

**Comment by abhijeet007rocks8** [comment]
Hi @Pranay105, i the issue still open? I would like to work upon the issue.
