### ISSUE TITLE
How to use Redshift as a data source on Appsmith

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#212]
Please cover the following topics in this guide -

1. Integrating the data source into Appsmith.
2. Fetching data from the connected data source.
3. Binding the data to a widget.
For documentation guidelines, click [here](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md).

**Comment by BRAVO68WEB** [comment]
Can you assign this to me?
@Pranay105

**Comment by parul5sahoo** [comment]
@Pranay105 Hey, can you assign me this issue?
