### ISSUE TITLE
How to use ElasticSearch as a data source on Appsmith 

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#214]
Please cover the following topics in this guide -

1. Integrating the data source into Appsmith.
2. Fetching data from the connected data source.
3. Binding the data to a widget.
For documentation guidelines, click [here.](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

**Comment by BRAVO68WEB** [comment]
Can you assign this to me?
@Pranay105

**Comment by mikidoodle** [comment]
Hey @Pranay105, If this is not already assigned, could you please assign it to me?

**Comment by Pranay105** [comment]
Yes, @achintya-7 . Assigning it to you!

**Comment by achintya-7** [comment]
sorry for that, can you reassign the issue to me. I have already made the document and just have to make PR request
