### ISSUE TITLE
How to work with GraphQL on Appsmith

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#215]
Please cover the following topics in this guide -

1. Integrating the data source into Appsmith.
2. Fetching data from the connected data source.
3. Binding the data to a widget.
For documentation guidelines, click [here.](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

**Comment by secure-crypto** [comment]
Hi @Pranay105 ! I would like to work on this issue next. Please assign it to me. Thanks.

**Comment by secure-crypto** [comment]
Hi @hetunandu @vihar ! Can I proceed with this. I am learning about GraphQL and how to integrate it with Appsmith.

**Comment by vihar** [comment]
@roshni-salpekar, @secure-crypto, please proceed with this issue. For reference, please look at  https://blog.appsmith.com/building-a-store-catalogue-management-system-using-appsmith-and-graphql.

The format of this guide can be similar to https://docs.appsmith.com/how-to-guides/how-to-work-with-google-sheets-on-appsmith
