### ISSUE TITLE
How to create Custom Charts on Appsmith

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#217]
Please make sure that your documentation has the following -

1. An Example app that shows the required widget.
2. Add screenshots for a better understanding of the topic.
3. Add code snippets wherever necessary.

For documentation guidelines, click [here](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md).

**Comment by roshni-salpekar** [comment]
hey @Pranay105  I would like to contribute to this issue

**Comment by vihar** [comment]
Hey @kalpeshT101, you can work on this issue, we have assigned it to you.

**Comment by devgossips** [comment]
Please assign me
