### ISSUE TITLE
[Docs]: Update custom widget guide

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#2177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Discord/slack/intercom Link if needed

https://theappsmith.slack.com/archives/C0341RERY4R/p1712303635833929

**Comment by harshilp24** [comment]
Update the doc into diff sections-

- Setup Custom Widget
- Passing Data from Custom Widget
- Passing Data from Appsmith to Custom Widget
- Etc.

**Comment by jnikhila** [comment]
duplicate https://github.com/appsmithorg/appsmith-docs/issues/2199
