### ISSUE TITLE
How to build auto-generated forms using the list widget

### ISSUE THREAD

**Issue by Pranay105** [appsmithorg/appsmith-docs#219]
Please make sure that your documentation has the following -

1. An Example app that shows the required widget.
2. Add screenshots for a better understanding of the topic.
3. Add code snippets wherever necessary.
For documentation guidelines, click [here.](https://github.com/appsmithorg/appsmith/blob/release/contributions/docs/CONTRIBUTING.md)

**Comment by Pradyuman7** [comment]
Hey @Pranay105, I am interested in working on this, can you please assign me this issue?
