### ISSUE TITLE
[Docs]: Missing Examples for Global functions

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2193]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Missing-Examples-for-Global-functions-1c7b4ccfdeb4401ab15b4eb2c03b76ef

**Comment by jnikhila** [comment]
duplicate #2351
