### ISSUE TITLE
[Docs]: Anthropic 

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2213]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Anthropic-32e8ac2f629346d4a4dc9b98d10e735b

**Comment by jnikhila** [comment]
Merged https://github.com/appsmithorg/appsmith-docs/pull/2184
