### ISSUE TITLE
[Docs]: Update steps for SSO setup Active Directory

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2225]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Update-steps-for-SSO-setup-Active-Directory-cb2728e15c9e45ef8d03d9c7b6b7a786

**Comment by jnikhila** [comment]
@trishaanand / @infinitetrooper - could you please add steps or pointers for update?

**Comment by jnikhila** [comment]
duplicate of #2228 and #2229
