### ISSUE TITLE
[Docs]: Add troubleshooting guide for MongoDB config

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2240]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Add-troubleshooting-guide-for-MongoDB-config-9d6a8c8494564488938d195bebb9e77c

**Comment by jnikhila** [comment]
Duplicate of #2237
