### ISSUE TITLE
[Docs]: Understanding Granular Access Control in Appsmith

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2246]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Understanding-Granular-Access-Control-in-Appsmith-4a690eb42bbb4b10b9e89095b059f829

**Comment by jnikhila** [comment]
Completed
