### ISSUE TITLE
[Docs]: setSelectedOption is documented as object instead of string

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith-docs#2265]
### Problem Statement

Hover suggestion when writing setSelectedOption() says it's a string but in the select widget documentation it says it is an object.

Also could use clarity on how to set it to null.  setSelectedOption(null) does not work but setSelectedOption("null") does.

![image](https://github.com/appsmithorg/appsmith-docs/assets/123981587/950c4566-9926-4dfe-b37d-6d9309ddb706)

### Other Relevant Links

https://docs.appsmith.com/reference/widgets/select

### Checklist

- [X] Reviewed existing documentation to ensure this request is not duplicated.
- [X] Attached relevant media or supporting materials like links to the PRD, feature recordings, Slack or Discord links, and any other relevant resources.

**Comment by eedwardsSGS** [comment]
The example still includes the {} braces, which does not work.  Instead the value that goes in as parameter must match the type of the value in the select.  So if the value is a string, the parameter must be a string, number -> number, etc.

**Comment by Nikhil-Nandagopal** [comment]
@eedwardsSGS thanks for pointing this out! @jnikhila could you please have a look?

**Comment by jnikhila** [comment]
Fixed (#2268) and deployed.
