### ISSUE TITLE
[Docs]: Update Google Sheets datasource reference for restricted access

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#2267]
### Problem Statement

When the access is allowed to only selected sheets, the users cannot insert data into the sheets that are not accessible. The reference document does not specify the information on restricted access.

### Use Cases / User query reference

Add the information for restricted access.

### Other Relevant Links

https://theappsmith.slack.com/archives/C0341RERY4R/p1715781493294259

### Checklist

- [X] Reviewed existing documentation to ensure this request is not duplicated.
- [X] Attached relevant media or supporting materials like links to the PRD, feature recordings, Slack or Discord links, and any other relevant resources.

**Comment by harshilp24** [comment]
done - https://docs.appsmith.com/connect-data/reference/querying-google-sheets#insert-one
