### ISSUE TITLE
[Docs]: Sync backup to S3 

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2280]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Sync-backup-to-S3-c8d7aed766d044d394a78f1b830514eb

**Comment by jnikhila** [comment]
duplicate - https://github.com/appsmithorg/appsmith-docs/issues/2279
