### ISSUE TITLE
Improving the embedding of YouTube Video in readme.md

### ISSUE THREAD

**Issue by Aarjav-Jain** [appsmithorg/appsmith-docs#231]
Link to the page which needs improvement :
https://github.com/appsmithorg/appsmith-docs/blob/v1.3/README.md?plain=1#L22

The embedding of the YouTube video can be improved

BEFORE:
<img width="744" alt="before" src="https://user-images.githubusercontent.com/77677344/135718032-5d726b0d-bbd4-4062-941f-f95f1cead2d6.PNG">

AFTER IMPROVEMENT:
Added the thumbnail to the youtube video as an hyperlink

![After](https://user-images.githubusercontent.com/77677344/135718027-c85e16be-9269-4d09-88c9-b3ef19bb2e80.png)

**Comment by Aarjav-Jain** [comment]
Should I work on this?

**Comment by asrajawat22** [comment]
Hi, I would like to work on this issue. Can you assigned this issue to me?

**Comment by javeriatabassum145** [comment]
Hello, I want to work on this. Can you assign it to me?
