### ISSUE TITLE
Issue with extended Markdown

### ISSUE THREAD

**Issue by AnTheMaker** [appsmithorg/appsmith-docs#234]
Hi there!
I noticed that across the Docs there are multiple extened Markdown Tags in use, which do not seem to work when viewing the content on GitHub. Some examples are:
```
{% hint style="success" %} ... {% endhint %}
```
or youtube embeds:
```
{% embed url="https://www.youtube.com/watch?v=mzqK0QIZRLs&feature=youtu.be" caption="" %}
```
They appear like the following when browsing the Repo on GitHub:

----
![grafik](https://user-images.githubusercontent.com/18481195/135725270-5691fce6-fbf8-420f-aea1-dcf047338493.png)
----

How should this be handled?
Should it be kept this way or should it be changed to GitHub-supported Markdown?

An idea would be, for example, to change "success" or "error" hints to GitHub "Quotes" like this:
> This is a quote

And youtube embeds could be changed to displaying the YouTube Thumbnail which links to the video on YouTube.
I'd be up to changing those things across the whole Repo, if you decide to do it that way.

Anyways, have a great day (and a great hacktoberfest!)
_An_

**Comment by saptarsi96** [comment]
I am willing to work on this issue.

**Comment by Nikhil-Nandagopal** [comment]
Hello, I'm sorry but this is not a valid issue. We use these extended tags because they need to render on gitbook
