### ISSUE TITLE
[Docs]: Integrate with AWS

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2345]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Integrate-with-AWS-b2ce3afe939749b9b2004c9c473b3a14

**Comment by jnikhila** [comment]
This is not supported at the moment in the product and the workaround to use JS is not a good option as the access and secret keys are needed to generate signature.
