### ISSUE TITLE
[Docs]: Tutorial - Basics

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2368]
## Problem Statement

To add new redirect urls for the  URLs that throw 404. Tagged by Google

## Other Relevant URLs

Draft: https://www.notion.so/Tutorial-Basics-7937d63a4a0b436e8b3c57b2218313ae

**Comment by jnikhila** [comment]
We are not going to work on this project at the moment as the user tests suggested that the docs are working.
