### ISSUE TITLE
[Docs]: Displaying Realtime data from kafka

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2441]
## Problem Statement

Displaying Realtime data from kafka

## Other Relevant URLs

Draft: https://www.notion.so/Displaying-Realtime-data-from-kafka-e2c4bf9ab8344f4a87cbaeb989d2c387
Slack/conversation:

**Comment by jnikhila** [comment]
https://community.appsmith.com/tutorial/display-real-time-data-kafka-confluent-cloud
