### ISSUE TITLE
[Docs]: Unable to Connect to a PostgreSQL DB from Appsmith hosted on Azure

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2448]
## Problem Statement

Unable to Connect to a PostgreSQL DB from Appsmith hosted on Azure

## Other Relevant URLs

Draft: https://www.notion.so/Unable-to-Connect-to-a-PostgreSQL-DB-from-Appsmith-hosted-on-Azure-d57a9ce1a78140a1ac69cd59bd9f4557
Slack/conversation:

**Comment by jnikhila** [comment]
https://github.com/appsmithorg/appsmith-docs/pull/2499
