### ISSUE TITLE
[Docs]: Provide documentation for installation on OpenShift 

### ISSUE THREAD

**Issue by mhohnerdnb** [appsmithorg/appsmith-docs#2449]
### Problem Statement

Related to the issues [[Feature]: Steps to deploy Appsmith on Openshift](https://github.com/appsmithorg/appsmith/issues/32392) and [[Feature]: Support arbitrary user ids for Appsmith's container image to properly work on Openshift ](https://github.com/appsmithorg/appsmith/issues/28828) I can find no documentation to actually deploy AppSmith on OpenShift either by Helm-Chart or otherwise. 

### Use Cases / User query reference

Add documentation, for example, as a sub page "Openshift" to this documentation page [Install Appsmith](https://docs.appsmith.com/getting-started/setup/installation-guides) with the specifics for a deployment on Openshift.

### Checklist

- [X] Reviewed existing documentation to ensure this request is not duplicated.
- [X] Attached relevant media or supporting materials like links to the PRD, feature recordings, Slack or Discord links, and any other relevant resources.

**Comment by jnikhila** [comment]
@mhohnerdnb - We don't officially support Open Shift, and hence the documentation is not available in our product docs. You can install Appsmith on Docker. Here's a detailed guide on how to Install Appsmith on [Docker](https://docs.appsmith.com/getting-started/setup/installation-guides/docker).
