### ISSUE TITLE
[Docs]: Format 2 - How to build an Appsmith app to monitor your other Appsmith app usage?

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2459]
## Problem Statement

Format 2 - How to build an Appsmith app to monitor your other Appsmith app usage?

## Other Relevant URLs

Draft: https://www.notion.so/Format-2-How-to-build-an-Appsmith-app-to-monitor-your-other-Appsmith-app-usage-6fd65767c9ed428b9cffd1c494178bd0
Slack/conversation:

**Comment by jnikhila** [comment]
Duplicate #2457
