### ISSUE TITLE
[Task]: Update Digital Ocean Video Tutorial on the Documentation

### ISSUE THREAD

**Issue by kevinblanco** [appsmithorg/appsmith-docs#2500]
### Problem Statement

Embedded video showcased on this page: https://docs.appsmith.com/getting-started/setup/installation-guides/digitalocean is no longer valid and needs an update; we just published the new video https://youtu.be/H4KDHWloSR4 . **Please update and keep embedding this new video (do not just link to the video, embed it as the current one)** 

### Use Cases / User query reference

Embedded video showcased on this page: https://docs.appsmith.com/getting-started/setup/installation-guides/digitalocean is no longer valid and needs an update; we just published the new video https://youtu.be/H4KDHWloSR4 . **Please update and keep embedding this new video (do not just link to the video, embed it as the current one)** 

### Audio/Video Recording

https://youtu.be/H4KDHWloSR4

### Checklist

- [X] Reviewed existing documentation to ensure this request is not duplicated.
- [X] Attached relevant media or supporting materials like links to the PRD, feature recordings, Slack or Discord links, and any other relevant resources.

**Comment by jnikhila** [comment]
@kevinblanco - the documentation steps and video steps are different. Has the interface at Digital Ocean changed? Please confirm. If so. we will have to delay the video embed until we update the steps in the doc so that the video and steps are in sync.

**Comment by jnikhila** [comment]
The documentation needs updating based on the interface changes at Digital Ocean.
