### ISSUE TITLE
[Docs]: Update Screenshots and Steps in Tutorials

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2517]
## Problem Statement

Update Screenshots and Steps in Tutorials

## Other Relevant URLs

Draft: https://www.notion.so/Update-Screenshots-and-Steps-in-Tutorials-386552b861bd476dae007fad1542655f
Slack/conversation:

**Comment by jnikhila** [comment]
We are not going to work on this project at the moment as the user tests suggested that the docs are working.
