### ISSUE TITLE
[Docs]: Update DigitalOcean Installation Guide

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2530]
## Problem Statement

Update DigitalOcean Installation Guide

## Other Relevant URLs

Draft: https://www.notion.so/Update-DigitalOcean-Installation-Guide-0fc38e2024584c6cb5883de404159a5a
Slack/conversation:

**Comment by jnikhila** [comment]
Duplicate of #2500
