### ISSUE TITLE
[Docs]: Fix-Dependabot Issue with Ask-ai modal

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2537]
## Problem Statement

Fix-Dependabot Issue with Ask-ai modal

## Other Relevant URLs

Draft: https://www.notion.so/Fix-Dependabot-Issue-with-Ask-ai-modal-c4ddfe3b2ead4c76a2cf9f2bfde308f0
Slack/conversation:

**Comment by jnikhila** [comment]
[Completed](https://github.com/appsmithorg/appsmith-docs/pull/2502)
