### ISSUE TITLE
[Docs]: Using different ports for Appsmith when using Caddy as a reverse proxy server

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2549]
## Problem Statement

Using different ports for Appsmith when using Caddy as a reverse proxy server

## Other Relevant URLs

Draft: https://www.notion.so/Using-different-ports-for-Appsmith-when-using-Caddy-as-a-reverse-proxy-server-107fe271b0e280c3a5def535387bd132
Slack/conversation:

**Comment by jnikhila** [comment]
Updated post - https://community.appsmith.com/solution/appsmith-ssl-different-port
