### ISSUE TITLE
[Docs]: Replace docs.appsmith.com embedded video 

### ISSUE THREAD

**Issue by kevinblanco** [appsmithorg/appsmith-docs#2571]
### Problem Statement

The video being currently embedded in the main docs.appsmith.com page (Appsmith in 100 seconds) is outdated and does not represent the current state of the product. We've produced a better, more recent video that can be embedded there. 

Please replace it with the following one: https://www.youtube.com/watch?v=jhyDI0e1o08 

### Use Cases / User query reference

Replace the "Appsmith in 100 seconds" video in the docs page with https://www.youtube.com/watch?v=jhyDI0e1o08

### Audio/Video Recording

https://www.youtube.com/watch?v=jhyDI0e1o08 

### Checklist

- [X] Reviewed existing documentation to ensure this request is not duplicated.
- [X] Attached relevant media or supporting materials like links to the PRD, feature recordings, Slack or Discord links, and any other relevant resources.

**Comment by KirankumarAmbati** [comment]
@Nikhil-Nandagopal @kevinblanco fixed and raised a PR for this issue

**Comment by jnikhila** [comment]
@kevinblanco - As discussed earlier, we can open a new ticket when the 100-minute video is updated.
