### ISSUE TITLE
[Docs]: Appsmith helm charts supports mounting custom-ca from values.yaml

### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2576]
## Problem Statement

Appsmith helm charts supports mounting custom-ca from values.yaml

## Other Relevant URLs

Draft: https://www.notion.so/Appsmith-helm-charts-supports-mounting-custom-ca-from-values-yaml-119fe271b0e280ddb2f2ead0b5af6915
Slack/conversation:

**Comment by jnikhila** [comment]
Duplicate #2623
