### ISSUE TITLE
[Docs]: Whitelist cs.appsmith.com when using a load balancer.



### ISSUE THREAD

**Issue by docs-appsmith** [appsmithorg/appsmith-docs#2611]
## Problem Statement

Whitelist cs.appsmith.com when using a load balancer.

## Other Relevant URLs

Draft: https://www.notion.so/Whitelist-cs-appsmith-com-when-using-a-load-balancer-124fe271b0e280c2860bc4df755fb312
Slack/conversation:

**Comment by jnikhila** [comment]
Duplicate #2512
