### ISSUE TITLE
Add triggeredRow property to the documentation

### ISSUE THREAD

**Issue by aswathkk** [appsmithorg/appsmith-docs#277]
I've seen that some users are still using `Table.selectedRow` instead of using `Table.triggeredRow` which causes unintentional effects. We need to add the usage of `Table.selectedRow` into the documentation to avoid this.

**Comment by jnikhila** [comment]
@danciaclara - Could you please help here, as there was an example added to docs for `Table.triggeredRow`?

**Comment by danciaclara** [comment]
Added - https://docs.appsmith.com/reference/widgets/table#reference-properties
