### ISSUE TITLE
Add documentation showing how to bind widget data to an API

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith-docs#295]
We have tutorials & steps showing how to bind data returned from an API to a UI widget. But we don't seem to have any handy documentation showing the inverse. If I wish to bind data from a widget to an API / DB query, there doesn't seem to be any tutorial around this. Seems like a basic use case that we've missed out on documenting.

**Comment by spark-c** [comment]
@danciaclara I'm not sure if I'm understanding right -- do you mean pulling data from a widget on the canvas and using it in a query? Unless I misunderstand, I think many of our examples throughout the docs/datasources demonstrate this with things like 

```javascript
// https://my-api.example.com/createuser
{
    "name" : {{ Form1.data.NameInput}},
    "email": {{ Form1.data.EmailInput}},
    "dob": {{ Form1.data.DobPicker }}
}
```

Or, do you mean something more like a proper tutorial?

**Comment by spark-c** [comment]
Closing -- was decided in review call that there are enough examples thru the docs for now, could revisit sometime later.
