### ISSUE TITLE
Changes needed in README.md

### ISSUE THREAD

**Issue by sohamsshah** [appsmithorg/appsmith-docs#30]
In the last line of the current README.md, the url is not properly linked in the markdown. Also there is some more revamping can be done in the README.md file of the current repository.

**Comment by sohamsshah** [comment]
I would love to take up this issue.

**Comment by sohamsshah** [comment]
Please find the related PR fixing this issue #31 [here](https://github.com/appsmithorg/appsmith-docs/pull/31)
Awaited to actively contribute towards AppSmith! Thank you!

**Comment by Nikhil-Nandagopal** [comment]
@sohamsshah the URL is linked correctly because we use gitbook for our documentation so the URL is using their markdown for embedding
https://docs.appsmith.com/
Please discuss the issue with a maintainer next time :)
