### ISSUE TITLE
Update phrase in introduction section

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith-docs#311]
In the introduction page, we've the following

> Here are five simple steps to create an app in Appsmith:

By steps, usually users understand a sequence of actions that someone need to complete in order to achieve something. The described points are not steps but are functionalities/features/use cases. Changing the text to something else seems more appropriate in this case.

**Comment by nayan-rafiq** [comment]
It can be like the following:

How does Appsmith work? -> What you can do with Appsmith?

Here are five simple steps to create an app in Appsmith: -> Here are top five use cases you can do with Appsmith:

**Comment by kasarchou** [comment]
Hello @nayan-rafiq i am trying to find the phrases you are talking about but it seems like the have already been resolved?

**Comment by AS-Laguna** [comment]
I'm available to make these changes.

**Comment by danciaclara** [comment]
was updated by https://github.com/appsmithorg/appsmith-docs/pull/701
