### ISSUE TITLE
Creating an Account seems inappropriate title

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith-docs#312]
In the homepage, the "Creating an Account" section title seems inappropriate. Better phrase may be: Running Appsmith, Running the Server, How to Run etc

**Comment by jnikhila** [comment]
@nayan-rafiq - The [introduction page](https://docs.appsmith.com) has underwent changes. Could you please verify the same?

**Comment by danciaclara** [comment]
@jnikhila I think we should close this
