### ISSUE TITLE
Add a sample query for aggregation in mongodb

### ISSUE THREAD

**Issue by nayan-rafiq** [appsmithorg/appsmith-docs#349]
The mongodb query documentation page has no example on how to write a aggregation query.

https://docs.appsmith.com/datasource-reference/querying-mongodb/mongo-syntax 

Need to add few examples on it.

**Comment by jnikhila** [comment]
@harshilp24 - Please verify this. CC: @danciaclara

**Comment by jnikhila** [comment]
@nayan-rafiq - The doc has [an example added for the Aggregate query](https://docs.appsmith.com/reference/datasources/querying-mongodb#aggregate). Please verify if this suffices.

**Comment by danciaclara** [comment]
Let's close this one too
