### ISSUE TITLE
[Feature]: Documentation for SSH Plugin

### ISSUE THREAD

**Issue by mojtab23** [appsmithorg/appsmith-docs#355]
### Summary
SSH plugin allows server-side commands to be called and return the output through the SSH.
We need to add documentation for this feature here. Link to feature: https://github.com/appsmithorg/appsmith/issues/2404

**Comment by danciaclara** [comment]
Closing the issue as this feature has not been prioritised yet. When it does get into development, we will create a new issue. cc: @rohan-arthur
