### ISSUE TITLE
JWT doc functionality questions

### ISSUE THREAD

**Issue by bcspragu** [appsmithorg/appsmith-docs#366]
Hi there!

I've been setting up an AppSmith deployment authenticated with SSO and going through the [JWT documentation](https://docs.appsmith.com/core-concepts/json-web-tokens-jwt), and I had a few questions:

1. Where does the `<<ENV_VARIABLE>>` syntax work?

From the docs:

> The environment variable APPSMITH_USER_OAUTH2_ACCESS_TOKEN stores access token. You can read the value of the access token by using it in between the angular braces<<>>.

I didn't see `APPSMITH_USER_OAUTH2_ACCESS_TOKEN` appear anywhere in the [appsmithorg/appsmith](https://github.com/appsmithorg/appsmith) codebase, and using double angle brackets in a datasource or query just passed along the string as a literal. Wrapping that in double curly brackets, e.g. `{{<<APPSMITH_USER_OAUTH2_ACCESS_TOKEN>>}}` produces `null`, but so does putting any invalid identifier between `{{ }}`.

2. Is `{{appsmith.user.idToken}}` supposed to be functional?

From the docs:

> You can read the value of an id token in your APIs/Queries by using a mustache sign {{}}.
> 
> {{appsmith.user.idToken}}

When I use `{{appsmith.user.idToken}}`, I get `{}`, meaning that `idToken` is an empty object. Looking through the codebase, the only time `idToken` appears is [here](https://github.com/appsmithorg/appsmith/blob/5022df91924c2cd7f4803c5c7ecd65a841ccf897/app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserProfileDTO.java#L48), where it's set to an empty map, which matches my experience. I have SSO configured through Google and that works fine.

**Comment by jnikhila** [comment]
@trishaanand - Could you please help here?

**Comment by danciaclara** [comment]
cc: @infinitetrooper

**Comment by infinitetrooper** [comment]
Hey @bcspragu  - yes, if you use OIDC or Google OAuth, you should be able to access the ID and Access token. ID Token on the client and Access Token will be replaced when the query is sent from the server. Attaching a couple of screenshots showing the usage. Let me know if you face any errors, you can open an issue at - https://github.com/appsmithorg/appsmith/issues. 

I'm closing this issue for now, please feel free to reopen it if you have additional queries.

![Capture-2023-03-15-171340](https://user-images.githubusercontent.com/16632903/225300026-e283ca86-3a18-4e46-8e5d-da2ad01cc6e1.png)
![Capture-2023-03-15-171218](https://user-images.githubusercontent.com/16632903/225300011-c51bf68b-bf42-4076-a8c3-04d8e680f470.png)
