### ISSUE TITLE
typo in tutorial

### ISSUE THREAD

**Issue by cebas** [appsmithorg/appsmith-docs#371]
In this section:
https://docs.appsmith.com/tutorials/building-a-store-catalog-manager/part-2-using-forms#connecting-multiple-pages
where it says: "Type **Add**ProductPage in Page Name field"
it must say "Type **New**ProductPage in Page Name field"

**Comment by jnikhila** [comment]
[Fixed](https://docs.appsmith.com/learning-and-resources/tutorials/building-a-store-catalog-manager/using-forms#connecting-multiple-pages).
