### ISSUE TITLE
duplicated paragraphs in tutorial

### ISSUE THREAD

**Issue by cebas** [appsmithorg/appsmith-docs#372]
in the section https://docs.appsmith.com/tutorials/building-a-store-catalog-manager/part-3-creating-interactive-views#accessing-properties-between-widgets of the tutorial seems to be some almost duplicate paragraphs:

- ProductNameInput should show the productName value of the selected row
- MrpInput should show mrp value of the selected row
- CategoryDropdown should show category value of the selected row
- ProductNameInput should show the value of column productName of the selected row
- MrpInput should show the value of column mrp of the selected row
- CategoryDropdown should show the value of column category of the selected row

**Comment by jnikhila** [comment]
[Fixed](https://docs.appsmith.com/learning-and-resources/tutorials/building-a-store-catalog-manager/creating-interactive-views#accessing-properties-between-widgets).
