### ISSUE TITLE
Update links to Sample Apps

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith-docs#374]
We're currently redesigning the [sample apps](https://docs.appsmith.com/sample-apps), and the links will need to be updated.

- [ ] Working with Tables
- [ ] Server-side Pagination
- [ ] Bulk insert/update
- [ ] Queries/APIs
- [ ] JS Object & Promises/Async-Await
- [x] Form
- [ ] Charts
- [ ] Appsmith Framework
- [ ] Date-Time
- [ ] Widgets
- [ ] UI Components
- [x] Utility

**Comment by jnikhila** [comment]
Available on [docs] (https://docs.appsmith.com/sample-apps#utility)
