### ISSUE TITLE
Broken Link: Building a Store Catalog Manager link `private instance` is broken

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith-docs#377]
Third paragraph, second link `private instance` gives a 404 error.

**Comment by jnikhila** [comment]
[Fixed](https://docs.appsmith.com/learning-and-resources/tutorials/building-a-store-catalog-manager).

**Comment by jnikhila** [comment]
[Fixed](https://docs.appsmith.com/learning-and-resources/tutorials/building-a-store-catalog-manager).
