### ISSUE TITLE
Outdated Reference: Build a Catalog tutorial references the Dropdown widget, which is now the Select widget

### ISSUE THREAD

**Issue by AS-Laguna** [appsmithorg/appsmith-docs#378]
There is a section [here](https://docs.appsmith.com/tutorials/building-a-store-catalog-manager/part-2-using-forms#adding-dropdown-widget-to-form) that contains references and links to the old Dropdown widget, which I believe is now the Select widget.

**Comment by karnatisrinivas** [comment]
Hello @AS-Laguna , I would like to give it a try!

**Comment by AS-Laguna** [comment]
Thanks @karnatisrinivas, but I think this article is being completely rewritten internally at the moment! I'm going to close it, but by all means please pick another issue to work on. We appreciate any contributions you choose to make!
