### ISSUE TITLE
docs start error: unknown block tag: embed

### ISSUE THREAD

**Issue by synuwxy** [appsmithorg/appsmith-docs#400]
## docs start error: unknown block tag: embed

I hope start appsmith-docs locally，but I have this error

```bash
$ gitbook serve
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 8 plugins are installed 
info: loading plugin "url-embed"... OK 
info: loading plugin "livereload"... OK 
info: loading plugin "highlight"... OK 
info: loading plugin "search"... OK 
info: loading plugin "lunr"... OK 
info: loading plugin "sharing"... OK 
info: loading plugin "fontsettings"... OK 
info: loading plugin "theme-default"... OK 
info: found 178 pages 
info: found 1239 asset files 
error: error while generating page "README.md": 

Template render error: (F:\workspace\github.com\appsmith-docs\README.md) [Line 22, Column 2]
  unknown block tag: embed
```

This is my environmental information

* OS: windows11
* CLI version: 2.3.2
* GitBook version: 3.2.3
* node version v14.17.1

I found that there is no book.json file in the project root directory，Is there a plugin missing?

**Comment by jnikhila** [comment]
@synuwxy - We have migrated from GitBook. The [repository README has instructions](https://github.com/appsmithorg/appsmith-docs/blob/main/README.md) to setup and run doc's locally.
