### ISSUE TITLE
Add steps for upgrading Appsmith instance to enterprise

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith-docs#405]
We should publish the content present at https://appsmith.notion.site/Getting-started-with-Appsmith-enterprise-edition-76a71071f4284fbca7a55058d13c8361 on our public documentation site. This page details the steps on how to upgrade an existing/new instance of Appsmith to the EE version.

**Comment by jnikhila** [comment]
[Documentation published](https://docs.appsmith.com/setup/upgrade-to-business-edition).

**Comment by jnikhila** [comment]
[Updated documentation](https://docs.appsmith.com/setup/docker) to add installation for a business edition.
