### ISSUE TITLE
Improve Telemetry section

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith-docs#418]
Currently, the telemetry section within Appsmith is outdated. We should remove the following sections immediately: 

* https://docs.appsmith.com/telemetry#docker-installation

Also, we should add UI screens to show how to disable telemetry within the product at: https://docs.appsmith.com/telemetry#disable-telemetry

Also, the subtitle of the page needs to be modified to: 

We ask you to opt-in to send us regular usage telemetry during the installation process. Even if you don't, we understand and appreciate your security requirements. Read on to understand more.

**Comment by jnikhila** [comment]
Doc updated.
