### ISSUE TITLE
Add documentation informing users how to downgrade their Appsmith instance

### ISSUE THREAD

**Issue by mohanarpit** [appsmithorg/appsmith-docs#425]
Self hosted Appsmith instances are geared for updating to a new version easily. But at times, users want to downgrade to a previous version of Appsmith using their backed-up data. We need to document this in our public documentation as well.

**Comment by jnikhila** [comment]
@mohanarpit - Does this [documentation](https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl#restore-appsmith-instance) suffices the need?
