### ISSUE TITLE
Typo in homepage (www.appsmith.com)

### ISSUE THREAD

**Issue by dxps** [appsmithorg/appsmith-docs#431]
Hey there!

I'm putting it here as I wasn't sure of the repo that the main website is based on.
Noticed a small typo in the image:
![image](https://user-images.githubusercontent.com/14140226/180995834-16645e75-fb40-4173-8115-5c09925c9ca1.png)

**Comment by vuiets** [comment]
Oops! Thanks for catching this @dxps.

@vihar is this something you can get fixed.

Even the card header `Theme Properties` is wrong.

**Comment by dxps** [comment]
Sure! Good catch as well @vuiets  :blush:

**Comment by tejasahluwalia** [comment]
This image are no longer used on the website, so closing the issue.
