### ISSUE TITLE
Link Corrections and other minor corrections

### ISSUE THREAD

**Issue by jerryjaimon** [appsmithorg/appsmith-docs#44]
Hi, 
I just noticed that the table of contents contains an unwanted entry in the Readme.md file. 
![image](https://user-images.githubusercontent.com/45946840/95674205-a9c74500-0bbf-11eb-8c01-eb4c1a984b4b.png)

I guess it is caused by the markdown heading tag, so I will remove that.
Also, I found a few grammatical errors and capitalization errors in the document(especially in the changelog file). So can I work on these? 

@Nikhil-Nandagopal

**Comment by Nikhil-Nandagopal** [comment]
@jerryjaimon, these seem like very minor issues so we're not currently accepting PRs with these types of fixes. Please have a look at our list of good first issues if you'd like to contribute :)
