### ISSUE TITLE
[Docs]: Migrate from Cloud to Self-Hosted Instance

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#440]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

NA

### Use cases or user requests

There could be a set of users who would want to migrate from the cloud to self-hosting. To help these users, we should provide documentation that they can follow and quickly move from cloud to self-hosted instance without loosing their apps and data.

Initial thoughts as discussed with @sharat87 
1 - Users are to follow the self-hosting guide for their chosen hosting platform.
2. - Migrate their applications from cloud to self-hosted instance.
3. Apps will need to either be exported from cloud and imported in their instance, or, if they are connected to a git repo, they can be imported from there.

Questions:
* How will the user data be migrated?
* Does migrate application also migrates datasources, queries, and connection strings? This looks challenging as the entire cloud database can't be given as backup. Can we make some provisions for this to happen?

**Comment by jnikhila** [comment]
@sharat87 / @sum35h - Please provide a first draft to help us document the same.

**Comment by sum35h** [comment]
How will the user data be migrated?
> The user data, including the workspace(s) cannot be migrated as of now. So the Admin will have to recreate the workspace and add the members on the self-hosted instance manually.

Does migrate application also migrates datasources, queries, and connection strings? This looks challenging as the entire cloud database can't be given as backup. Can we make some provisions for this to happen?
> Both ways of importing (gitsync and import json) migrates everything except the data-source connection-string/ credentials. The admin will have to re-enter those on the self-hosted instance when importing an app from the cloud.

**Comment by jnikhila** [comment]
@sum35h and @sharat87 - Could you please confirm the outcome?

**Comment by sharat87** [comment]
The details in the "Initial thoughts" in the issue description sound great. Let's add details to that and it should be enough. Beyond that I'm not sure what I can help with here. Can you help rephrase what I can help with please?
