### ISSUE TITLE
[Docs]: Update - Local DB and APIs

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#445]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/advanced-concepts/more/how-to-work-with-local-apis-on-appsmith

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C0341RERY4R/p1663575620132859

### Describe the problem

The user was trying to connect to the DB server hosted on the same machine as Appsmith. Hence they initially used localhost as the IP address, but when that didn't work, they tried to use their server name as the IP address which was not correct. 

### Describe the improvement

- Make the doc comprehensive to add more details and a summary for the embedded videos.
- Use search terms that users are looking for so that the doc can be bumped up the search results. (At present the doc is not available in the top 3)

### Why do you think this change is needed?

* ~The doc is not available in the top 3/5 search results, so discoverability is a problem~. --> **Resolved as part of the quick fix**.
 * Though the embedded video is helpful and will help users resolve the issue, adding a summary of the video and steps to the doc will be helpful for users.

**Comment by jnikhila** [comment]
@sumitsum - Please add more details, if I've missed anything.

**Comment by sumitsum** [comment]
Adding to what is mentioned in the description: 
- The main heading for the page that contains the info is `Local DB and APIs` - Can we change this to include the following two phrases / words: `connect to local DB` , `localhost` ?
- Can we change the order of the solution mentioned on the page i.e shift the `ngrok` solution down and pull up the other solution since that one is easier to implement vs the `ngrok` solution.

**Comment by jnikhila** [comment]
@sumitsum - These changes are done as part of quick fix. 
* The localhost term is added to the page and sub section. 
* The restructuring of the content is done and raised a GitBook CR for your review.
Do you mean to change the heading of the page from `Local DB and APIs` to `Connect to localhost`

**Comment by jnikhila** [comment]
@sumitsum - The quick fix doc is [published](https://docs.appsmith.com/advanced-concepts/more/how-to-work-with-local-apis-on-appsmith):
Following are the quick fixes:
 - Discoverability issue is resolved (doc is listed in top 3):
        - Title changed
        - localhost keyword added to title
        - doc content
 - Restructing of the content
       - Subheadings added 
             - host.docker.internal
             - ngrok
       - host.docker.internal section moved up for helping users quickly resolve issues

**Comment by jnikhila** [comment]
The [PR](https://github.com/appsmithorg/appsmith-docs/pull/551) is ready for review
