### ISSUE TITLE
[Docs]: Error - This value does not evaluate to type Array<Object>

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/help-and-support/troubleshooting-guide/widget-errors

### Describe the problem

Users see this error on the Table Data property mostly when the data is not bound correctly on the table.

### Describe the improvement

Troubleshooting information related to the above error needs to be documented so that users can be unblocked quickly.

### Why do you think this change is needed?

One of the most frequently searched errors on the Omnibar.

**Comment by jnikhila** [comment]
@danciaclara - Could you please also add the search term users are using?

**Comment by danciaclara** [comment]
@jnikhila These are errors that the user searched on Omnibar as is. I'll be adding a few more.

**Comment by jnikhila** [comment]
Already [Documented](https://docs.appsmith.com/help-and-support/troubleshooting-guide/js-errors#data-type-evaluation-errors).
