### ISSUE TITLE
[Docs]: Error - This value does not evaluate to type string

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Users see this error mostly when the data is not bound correctly on the Text widget or on a query that return a string value.

### Describe the improvement

Troubleshooting information related to the above error needs to be documented so that users can be unblocked quickly.

### Why do you think this change is needed?

One of the most frequently searched errors on the Omnibar.

**Comment by danciaclara** [comment]
@bharath31 Hey we want to know how to document such errors. Firstly, in what scenarios will a user see this error. at the moment, we only know that users will see it when they try to bind or display non-string data in a widget which expects data in string format? Is there anything else. Also suggestions that the users can do to get into the required format. Would you the FE team be able to give us a small draft around the cause and solution to this message?

**Comment by bharath31** [comment]
@danciaclara this is a TypeError similar to the ones [already documented](https://docs.appsmith.com/help-and-support/troubleshooting-guide/js-errors#data-type-evaluation-errors). I see that we currently have cause and solution for array and boolean data types. We can expand the same to String and probably other data types too(Number, Object)
