### ISSUE TITLE
[Docs]: Update - Queries

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/data-access-and-binding/querying-a-database

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C0341RERY4R/p1664167755129549

### Describe the problem

The users often write queries that are not optimized and expensive for large data sets and impact the client's performance also.

### Describe the improvement

Add tips to the documentation that will help users write efficient queries.

### Why do you think this change is needed?

This is needed to guide the users in the right direction for writing optimized queries.

**Comment by danciaclara** [comment]
Completed by #851
