### ISSUE TITLE
[Docs]: Add cell borders property in Table widget

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith-docs#483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/10995

### Release Date

Already in release

**Comment by jnikhila** [comment]
@jsartisan - Could you please share a first draft and the loom video for this?

**Comment by jsartisan** [comment]
![image](https://user-images.githubusercontent.com/6636360/197757710-84afc9b0-6052-4723-86be-d55cdc154e52.png)
@jnikhila just added this style property and linked the PR that explains the property in the style section of table widget docs.

**Comment by somangshu** [comment]
@jnikhila why is this issue not closed, the PR says the change is already added

**Comment by jnikhila** [comment]
@somangshu - the issue is in the done pipeline, so it's completed. @spark-c - Is anything pending on this issue? Could we close it?

**Comment by spark-c** [comment]
Resolved by #507
