### ISSUE TITLE
[Docs]: Add readonly property for rating widget

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith-docs#496]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/17141

### Release Date

21 Oct

**Comment by jsartisan** [comment]
Added this property in rating widget
![image](https://user-images.githubusercontent.com/6636360/197758167-a60ff1ba-2722-4363-9e9f-a1683c2bd174.png)

Also, linked the PR.

**Comment by Pranay105** [comment]
@spark-c can you pick this up and close it ASAP.
