### ISSUE TITLE
[Docs]: Document how to exit out of the navigation loop due to JS on page load

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/writing-code/javascript-editor-beta#debugger-statements

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/CGBPVEJ5C/p1666223396613649

### Describe the problem

When a user tries to write a page load query that contains logic to navigate some other page. and if the logic is not conditional then there is no way for the user to change the logic, as going to that page will just navigate to another page.

This will lead to being stuck in a loop, and there is no way other than to export the app, modify the logic and import it, which is not a great experience.

### Describe the improvement

We can add a section under Troubleshooting -> JS Errors specifying this navigation loop and a brief explanation on how to solve the issue and link to the debugger section in the docs - https://docs.appsmith.com/core-concepts/writing-code/javascript-editor-beta#debugger-statements

### Why do you think this change is needed?

This would make the issue and the resolution more discoverable in case users face it.

**Comment by Pranay105** [comment]
@jnikhila can you look into this?

**Comment by jnikhila** [comment]
@danciaclara / @Rishabh-Rathod - As there is no error message displayed on the app for users to figure out that the query is stuck in the navigation loop, we won't have one to add in the troubleshooting section.

However, in the existing JS Errors page, we have a dedicated section for [debugging](https://docs.appsmith.com/help-and-support/troubleshooting-guide/js-errors#debugging), should we add these details there and create a short video explaining a resolution. 

Could you please also help out with keywords that users are searching for? I could add the terms to the doc so that it becomes easily discoverable.

**Comment by Rishabh-Rathod** [comment]
IMO it seems like an `Application Error` and as a user I would try to find a resolution here https://docs.appsmith.com/help-and-support/troubleshooting-guide/application-errors#page-access-error

Keywords - `navigateTo` , `onPageLoad function`, `page not accessible`, `can't route to page`

**Comment by Rishabh-Rathod** [comment]
@jnikhila No, the user won't see any error for such cases. 

If a user adds logic to navigate to another page on the load of the page. 
- Appsmith works as expected and hence no error. 
- but the user will not be able to access that page. 

if trying to find help in docs, IMO [page-access-error](https://docs.appsmith.com/help-and-support/troubleshooting-guide/application-errors#page-access-error) would be the closest title to the problem user is facing. 

My suggestion is to maybe add a new sub-section in `application-errors` close to `page-access-error`.

**Comment by jnikhila** [comment]
I understand where you are coming from, and I feel that the page access error will be an appropriate place to document this. I guess we can add a subsection to [Page Access Error](https://docs.appsmith.com/help-and-support/troubleshooting-guide/application-errors#page-access-error)

## Page access error
.
.
.
### Unable to access page
You added a `navigateTo` logic in your JS object and enabled the JS object by binding it to the `on page load`  ......

Something like the above. Your thoughts? CC: @danciaclara

**Comment by danciaclara** [comment]
This is an issue that is encountered when someone writes JS functions that run on page load and end up getting stuck due to navigateTo action. How about instead of under 'Page access error', we add a new section called 'Infinite loop'  under JS errors and put this content there? In this case, I'm pretty certain users know it is because of their JS function that they are stuck in that loop and they need to know how to exit out of it. so they will most likely search under JS errors.

**Comment by jnikhila** [comment]
It makes sense. @Rishabh-Rathod - Your thoughts??

P.S. - We just won't have a screenshot to add to it which I guess is okay as there is no error message shown to the user.

**Comment by danciaclara** [comment]
It's fine not to have a screenshot. The infinite loop issue can occur due to any reason. NavigateTo is probably just one instance. it could also happen to opening modals, for example. Our main aim here to let them know how to exit out of that loop in case they a function running on page load
