### ISSUE TITLE
[Docs]: Table widget add new row feature

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith-docs#522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/13672

### Release Date

Nov 10 2022

### First Draft

https://www.notion.so/appsmith/Table-add-new-row-c3ed0d4c5d1e4ee29077e084df3830b8

### PRD

https://www.notion.so/appsmith/Adding-a-new-row-in-the-table-0ec90544d26c4c25ab1f9b2504e919a1

**Comment by jnikhila** [comment]
@spark-c - Could you please look into this?

**Comment by spark-c** [comment]
I'm experimenting with where is best to fit the new feature content will have a PR soon to discuss

**Comment by spark-c** [comment]
After review of the draft, the scope of this ticket is expanding a bit to be more of a rehaul of the inline-editing page of the Table widget docs.

**Comment by jnikhila** [comment]
@spark-c - Let's not block the release of this ticket due to Rehaul changes. You can create a separate PR for rehaul changes once the doc changes for this ticket are done.

**Comment by spark-c** [comment]
Will make test/video showing steps ASAP

**Comment by spark-c** [comment]
Merged
