### ISSUE TITLE
Youtube embeds not responsive

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith-docs#545]
I noticed that the Youtube embeds on the new docs site don't scale with window size. In addition to mobile devices, this is noticeable on 720p screens as well as on higher resolutions when the browser window is not fullscreen or is oriented vertically.

> 1080x1920p (vertical orientation)
![as_embed_size_bug](https://user-images.githubusercontent.com/51402465/199883425-1c12fc0b-e1ed-4b99-91f8-2065b451032a.png)

---

> 1280x720p
![as_1280_720](https://user-images.githubusercontent.com/51402465/199883511-a4b5f2a9-d685-4354-9c92-2ee06e0a11c1.png)

---

> (browser responsive mode) Google Pixel 5

![as_google_pixel_5](https://user-images.githubusercontent.com/51402465/199883552-48b14fa4-eafc-4a5f-aa76-deae2854e677.png)

**Comment by Pranay105** [comment]
@tejasahluwalia Can you help to fix this?

**Comment by tejasahluwalia** [comment]
> @tejasahluwalia Can you help to fix this?

Yup, will take care.
