### ISSUE TITLE
[Docs]: update Table.selectedRow with table.triggeredRow

### ISSUE THREAD

**Issue by sbalaji1192** [appsmithorg/appsmith-docs#560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/learning-and-resources/tutorials/building-a-store-catalog-manager/creating-interactive-views

### Discord/slack/intercom Link

https://github.com/appsmithorg/appsmith/issues/11403#issuecomment-1311874727

### GitBook Insights searchTerms or link

N/A

### Google Analytics - search terms or a link

N/A

### Describe the problem

As part of the https://github.com/appsmithorg/appsmith/issues/11403, we have changed the behavior of row selection when a button inside a row is clicked. As a result, an example in the docs has become invalid. So we need to change it as well.
please refer https://github.com/appsmithorg/appsmith/issues/11403#issuecomment-1311874727

### Describe the improvement

Instead of `ProductsTable.selectedRow` we should be using the `ProductsTable.triggeredRow`.

### Why do you think this change is needed?

This fixes a stale example in the docs.

**Comment by jnikhila** [comment]
@sbalaji1192 - I can read column values using `TableName.selectedRow`. Could you please add a loom video explaining the issue?

**Comment by sbalaji1192** [comment]
@jnikhila Previously clicking on a button in a row used to select the corresponding row. But with the changes we did in https://github.com/appsmithorg/appsmith/issues/11403, we are not selecting the corresponding row. So in the use case mentioned in the docs (linked in the description), we're using the `TableName.selectedRow` to populate the form once the edit button has been clicked. This will no longer work. we should be using the `TableName.triggeredRow`.
