### ISSUE TITLE
[Docs]: Add info on how to report security vulnerabilities on FAQ

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/faq

### GitBook Insights searchTerms or link

na

### Google Analytics - search terms or a link

na

### Describe the problem

Users ask about how to report security issues that they encounter and if there is a bounty program

https://www.notion.so/appsmith/When-Users-Want-to-Report-Security-Vulnerabilities-8d6938c33fc44fb7a9f2e179dc65f676

### Describe the improvement

add it

### Why do you think this change is needed?

many users have asked for it

**Comment by spark-c** [comment]
[PR here](https://github.com/appsmithorg/appsmith-docs/pull/654)
