### ISSUE TITLE
[Docs]: Add solution for JS error - Failed to execute postMessage...... could not be cloned

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/help-and-support/troubleshooting-guide/js-errors

### GitBook Insights searchTerms or link

na

### Google Analytics - search terms or a link

na

### Describe the problem

https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100101847#part_id=comment-164629100101847-15331420809

### Describe the improvement

na

### Why do you think this change is needed?

na

**Comment by danciaclara** [comment]
@satbir121 Would you able to give us more info on this error and if we should document it under Troubleshooting

**Comment by bharath31** [comment]
@satbir121 ICYMI ^ 

We should also add a linting error to prevent users from running into this state. [Slack conversation](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1671024480334019)
