### ISSUE TITLE
Weekly changelogs are missing since June :( 

### ISSUE THREAD

**Issue by naqushab** [appsmithorg/appsmith-docs#59]
Great work on this project. I know the work is fast paced but a periodic changelog would help. Not as fast as weekly but a periodic one.

**Comment by hetunandu** [comment]
Hey @naqushab we maintain a basic changelog here 
https://github.com/appsmithorg/appsmith/releases

But looks like it is not getting automated and set in the docs. @Nikhil-Nandagopal any ideas for this?

**Comment by naqushab** [comment]
Thanks this helps.

**Comment by Nikhil-Nandagopal** [comment]
Right now we don't do weekly releases but we'll be sure to write more information when we do create a release :)
