### ISSUE TITLE
[Docs]: Automatic height updates for widgets based on contents (Auto Height)

### ISSUE THREAD

**Issue by riodeuno** [appsmithorg/appsmith-docs#616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/11038

### Release Date

29th November, 2022

### First Draft

https://github.com/appsmithorg/appsmith/issues/13395

### Discord/slack/intercom Link if needed

https://app.frontapp.com/open/top_5b970

### PRD

https://github.com/appsmithorg/appsmith/issues/11038

### Test plan/cases

https://github.com/appsmithorg/TestSmith/issues/1771

### Use cases or user requests

- Users have complained that invisible widgets still take up space
- Team members have suggested that text widget doesn't automatically show all text
- Users have mentioned that Table widget and List widget should expand based on contents.

**Comment by danciaclara** [comment]
@riodeuno Couldn't find the first draft for this feature. Let me know if I'm looking in the wrong place. 

Also I see the release date is 29th Nov. Is this going out today?  

cc: @jnikhila
