### ISSUE TITLE
[Docs]: Table widget: Updated Row property documentation

### ISSUE THREAD

**Issue by keyurparalkar** [appsmithorg/appsmith-docs#618]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/table/inline-editing#updatedrow

### Describe the problem

There is a change in how the `updatedRow` logic works. Please refer to the [issue](https://github.com/appsmithorg/appsmith/issues/15486) and [PR](https://github.com/appsmithorg/appsmith/pull/18225) from the appsmith repo.

### Describe the improvement

Below are the changes that need to be made.

### Updated Row

This property consists of the details of the row that recently got updated. Irrespective of the update mode, the `updatedRow` property consists of the row that got recently updated. 

The default value for this property is an object with keys as column names and blank string as its values. For example, 

```jsx
{
	"step": "",
	"task": "",
	"status": ""
}
```

The value gets available as soon as a user updates a table cell. Not edits, but updates.

The `updatedRow` property will get reset to the default value whenever the value is saved(onSave) or when it is discarded(onDiscard).

**Comment by dilippitchika** [comment]
@jnikhila @spark-c this change looks good to me, can we please review it?
