### ISSUE TITLE
[Docs]: Dynamic Menu Items - Menu Button Widget

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith-docs#636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/pull/17652

### Release Date

Merged into release on 1 Dec, 2022

### First Draft

[PR Here](https://github.com/appsmithorg/appsmith-docs/pull/649)

### Loom video

[Here's an Unlisted YouTube Video](https://www.youtube.com/watch?v=ajzBkooI7CE)

### PRD

https://github.com/appsmithorg/appsmith/issues/12362#issuecomment-1202023433

### Use cases or user requests

A popular use case is [documented here](https://github.com/appsmithorg/appsmith/issues/12362) in the issue description.

**Comment by dhruvikn** [comment]
This is a WIP. I'll update here once it's ready to review.

**Comment by dhruvikn** [comment]
Have raised a PR #649 for this. Have also attached the first draft and video links in the issue description above.

cc: @dilippitchika @somangshu

**Comment by dilippitchika** [comment]
@dhruvikn can you fix the review items?

**Comment by dhruvikn** [comment]
Yes @jnikhila

**Comment by jnikhila** [comment]
@cokoghenun - Tagging you here as we need a new video for Menu Button Widget.
