### ISSUE TITLE
[Docs]: Table Widget

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/table
https://docs.appsmith.com/reference/widgets/table/column-settings

### Describe the problem

Rehaul the below docs:

* Table - [Landing Page](https://docs.appsmith.com/reference/widgets/table)
* Column Settings](https://docs.appsmith.com/reference/widgets/table/column-settings)

### Describe the improvement

Rehaul the docs
To analyze if https://docs.appsmith.com/core-concepts/data-access-and-binding/displaying-data-read/display-data-tables page data can be added to table widget.

**Comment by spark-c** [comment]
[PR available here](https://github.com/appsmithorg/appsmith-docs/pull/723) for review

**Comment by danciaclara** [comment]
Related 
https://github.com/appsmithorg/appsmith/issues/5426
https://github.com/appsmithorg/appsmith/issues/8210
