### ISSUE TITLE
[Docs]: Writing Code and Sub Pages

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/writing-code

### Describe the problem

Restructuring the content

### Describe the improvement

Rehaul the docs. Also add the accessing of attributes/column names with spaces.

**Comment by jnikhila** [comment]
The following pages will be worked on as part of this ticket:
-  [Writing code Landing Page](https://docs.appsmith.com/core-concepts/writing-code)
- [Creating Workflows](https://docs.appsmith.com/core-concepts/writing-code/workflows)
- [JavaScript Promises](https://docs.appsmith.com/core-concepts/writing-code/javascript-promises)
- [External Libraries](https://docs.appsmith.com/core-concepts/writing-code/ext-libraries)
- [Appsmith Framework Landing Page](https://docs.appsmith.com/reference/appsmith-framework)

**Comment by danciaclara** [comment]
#603
