### ISSUE TITLE
[Docs]: Button Widget

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/button

### Describe the problem

Restructuring

### Describe the improvement

Rehaul

**Comment by danciaclara** [comment]
Duplicate of #20019

**Comment by danciaclara** [comment]
@spark-c I see that you have opened a duplicate ticket on the other repo https://github.com/appsmithorg/appsmith/issues/20019 . Can you please close that and raise a PR for this one please?
