### ISSUE TITLE
[Docs]: Support OnFocus and OnBlur for a few widgets

### ISSUE THREAD

**Issue by dilippitchika** [appsmithorg/appsmith-docs#668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/6452

### Release Date

v1.8.13

### First Draft

#669 

### Loom video

[Loom](https://www.loom.com/share/4a7eb406ccd74dfba09e56045068ccd7)

### PRD

https://appsmith.notion.site/Widget-onFocus-and-onBlur-events-36fc98f9d0d04ce0b369247e91e01e5b

**Comment by jnikhila** [comment]
Opened as we'll merge the PR for changes once the engineering ticket is released. @dilippitchika - FYI

**Comment by jnikhila** [comment]
Opened as we'll merge the PR for changes once the engineering ticket is released. @dilippitchika - FYI
