### ISSUE TITLE
[Docs]: Branding

### ISSUE THREAD

**Issue by jsartisan** [appsmithorg/appsmith-docs#674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/15828

### Release Date

15 December 2022 / v1.8.13

### First Draft

#680 

### PRD

https://www.notion.so/appsmith/Branding-and-whitelabeling-798a3d121bee4922b8b20d00e5c07572

**Comment by dilippitchika** [comment]
Loom - https://www.loom.com/share/f1a8bc754949425cb92dfa2159a09060

**Comment by danciaclara** [comment]
Thanks @jsartisan @dilippitchika. Do you think it would be ok to name this as 'App Branding' in our documentation?

**Comment by dilippitchika** [comment]
Since it's not just limited to app but to whole of appsmith @danciaclara i don't know if adding the prefix app is useful here

**Comment by danciaclara** [comment]
Ok in that context, then App Branding wouldn't make sense. We can leave it as 'Branding'

**Comment by spark-c** [comment]
[Branding PR](https://github.com/appsmithorg/appsmith-docs/pull/680) now in review
