### ISSUE TITLE
[Docs]: Add A Troubleshooting guide for Dynamic Menu

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

NA

### Use cases or user requests

Add a troubleshooting section under widget errors for 'source array has more than 10 items.

If the dynamic source array has more than 10 items, the `SourceData` fields show an error message: `Source data cannot have more than 10 items`.

**Comment by danciaclara** [comment]
Closing this issue as the troubleshooting guide in itself is not extra helpful. The callout in the widget reference guide is enough - https://docs.appsmith.com/reference/widgets/menu-button#dynamic 

Besides there is nothing more we are saying besides what is already in the error message. cc: @jnikhila
