### ISSUE TITLE
[Docs]: Add for clearstore and removeValue

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

NA

### Use cases or user requests

Add docs to `clearStore()` and `removeValue()` functions.

**Comment by danciaclara** [comment]
Clear store - clear all the values in the local storage
Remove value - clears the value of the specified key in the local storage
