### ISSUE TITLE
[Docs]: Create Mock API to update the Custom Auth to update API example

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/advanced-concepts/how-to-implement-custom-authentication-on-appsmith

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C0341RERY4R/p1671520574332409?thread_ts=1670867237.511019&cid=C0341RERY4R

### Describe the problem

The Auth- APis are using free heroku database. Heroku has discontinued the free tier.

### Describe the improvement

Update the example and modify the APIs for this.

**Comment by jnikhila** [comment]
@vihar - Please review/add details.

**Comment by spark-c** [comment]
@vihar Do you know if there is a new example Auth API that we have set up? I've removed the outdated details, I have a place that I can add new deets in if we've got them. :)

**Comment by spark-c** [comment]
This ticket will be resolved with [this PR](https://app.zenhub.com/workspaces/user-education-pod-61c01739f309a80011b48267/issues/gh/appsmithorg/appsmith-docs/879).
