### ISSUE TITLE
[Docs]: Add feedback widget in Documenation

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

na

### Release Date

na

### Release Number

 na

### Use cases or user requests

In Gitbook we had a feedback widget with emojis where users could rate whether the page is useful. 
<img width="319" alt="Screenshot 2022-12-21 at 23 43 36" src="https://user-images.githubusercontent.com/32227135/208975248-4fdfea32-d506-47f4-b62b-2408ff2fb9ae.png">

This is very important information for us to track. Docusaurus has this feature planned in their roadmap, but until then, we should build this using Swizzle.
https://happyreact.com/blog/feedback-widget-in-docusaurus

**Comment by jnikhila** [comment]
@danciaclara - The [link](https://happyreact.com/blog/feedback-widget-in-docusaurus) uses Docusaurus Footer. But as we are going to remove the footer as part of #519, we will create a new component to add this.

**Comment by jnikhila** [comment]
Based [on this discussion](https://theappsmith.slack.com/archives/C048H8SEJ8K/p1680509736880889) - We'll need to evaluate the best possible way forward. Moving it back to Backlog ready pipeline.
