### ISSUE TITLE
[Docs]: Add a Troubleshooting guide for Schema Mismatch

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#700]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/pull/18844

### Release Date

01-Jan-2023

### Release Number

NA

### Discord/slack/intercom Link if needed

https://theappsmith.slack.com/archives/C02MUD8DNUR/p1671730051394859?thread_ts=1671186192.790739&cid=C02MUD8DNUR

### Use cases or user requests

To create a troubleshooting guide that talks about mandatory upgrade paths, How to find out if you need to use one, and how to use the one you need.

**Comment by nidhi-nair** [comment]
@jnikhila here's the draft for this troubleshooting guide: https://www.notion.so/appsmith/Server-keeps-shutting-down-with-Schema-Mismatch-error-2d081c2b257d4c78a83ee375d927e33a

Please let me know if you need more info here.

**Comment by jnikhila** [comment]
@nidhi-nair - Thanks for sharing this.
