### ISSUE TITLE
[Docs]: PostgreSQL 

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#713]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

NA

### Documentation Link

https://docs.appsmith.com/reference/datasources/querying-postgres

### Discord/slack/intercom Link

NA

### Describe the problem and improvement.

- Restructure the doc
- Linter

**Comment by danciaclara** [comment]
completed by https://github.com/appsmithorg/appsmith-docs/pull/906
