### ISSUE TITLE
[Docs]: Dynamic Menu Items - Table Widget

### ISSUE THREAD

**Issue by dhruvikn** [appsmithorg/appsmith-docs#715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/17955

### Release Date

Will merge to release possibly by 30 Dec, 2022

### First Draft

[PR here.](https://github.com/appsmithorg/appsmith-docs/pull/716)

### Loom video

https://user-images.githubusercontent.com/22471214/209994444-dafa3414-737e-4139-8d75-9928744ab72f.mp4

### Test plan/cases

https://github.com/appsmithorg/TestSmith/issues/2128

### Use cases or user requests

PR here - https://github.com/appsmithorg/appsmith/pull/18945

This feature allows users to use dynamic menu items (same as menu button widget) in Menu Button Column Type inside the Table Widget.

**Comment by dhruvikn** [comment]
@jnikhila @danciaclara, PR https://github.com/appsmithorg/appsmith-docs/pull/716 was approved by @somangshu. Please take a look.

**Comment by dhruvikn** [comment]
Hi @jnikhila @danciaclara, the engineering issue https://github.com/appsmithorg/appsmith/issues/17955 was merged into release last Friday (30th Dec). Just keeping you folks in the loop.

cc: @dilippitchika

**Comment by jnikhila** [comment]
Thanks @dhruvikn.
@Pranay105 - could you please look into this?
