### ISSUE TITLE
[Docs]: multi-line input and auto-resize textarea

### ISSUE THREAD

**Issue by somangshu** [appsmithorg/appsmith-docs#729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/pull/19141

### Release Date

16-01-22

### Release Number

1.9.5

### Discord/slack/intercom Link if needed

https://theappsmith.slack.com/archives/C02JV8G1MP0/p1672922573692979

### Use cases or user requests

Update the [input widget](https://docs.appsmith.com/reference/widgets/input) and amend the property - [data type](https://docs.appsmith.com/reference/widgets/input#data-type) for new value - `multi-line`. Also, cross-referencing to the [auto-height](https://docs.appsmith.com/reference/widgets#height) doc.

**Comment by jnikhila** [comment]
@somangshu - Is this ready for the doc team?

**Comment by somangshu** [comment]
I dont think so @jnikhila 

cc @ankurrsinghal can you please link the doc PR here and move this to user education pod's backlog

**Comment by jnikhila** [comment]
@somangshu - I've updated the ticket with details and added it to Use cases or user requests section in description. Please review. Once happy please add 'Ready for Doc team' label and we can take it ahead.
