### ISSUE TITLE
[Docs]: “How to Use Notion as a Database on Appsmith” guide

### ISSUE THREAD

**Issue by ichik** [appsmithorg/appsmith-docs#736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

NA

### Documentation Link

https://docs.appsmith.com/learning-and-resources/how-to-guides/use-notion-as-database-on-appsmith

### Describe the problem and improvement.

There are a few inaccuracies in the guide:
- Tab label in Notion's UI has changed, `Integrations` is now called `Connections`. This is both outdated on a screenshot and in guide's text.
- The type of request that is needed to [query Notion's database API](https://developers.notion.com/reference/post-database-query) is `POST`, screenshot falsely indicate that it's `GET`
- It is worth noting that the created “connection” in Notion needs to be added to the Notion page containing the database (top-right three dots menu → Connections → Add connections)
- Notion's API version has changed to `2022-06-28` ([ref](https://developers.notion.com/reference/versioning))

**Comment by danciaclara** [comment]
Hiding this page on the docs for now as these will move to the community portal
