### ISSUE TITLE
[Docs]: Add Appsmith Architecture docs

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#745]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

End of Jan

### Release Number

NA

### Use cases or user requests

Architecture documentation is an important part of product documentation because it provides a clear and detailed understanding of the system's design and structure. 
To add a new section under - Reference. 

* Architecture - This details out the deployment architecture, which is based on Docker installation. Appsmith installations, even on different platforms, are based on Docker.

**Comment by danciaclara** [comment]
Propsed Outline cc: @jnikhila 

# Appsmith Architecture
      [Intro]

## Self-hosted instance architecture
      [Image]

## How it works
      [Explanation of each element in the image and how it works. here we can also make a mention of fat container setup]

## Process management
      [Intro]

### Docker
### Kubernetes

**Comment by danciaclara** [comment]
https://github.com/appsmithorg/appsmith/issues/3600
