### ISSUE TITLE
[Docs]: When field is hidden in a json form allow user to set if they want to use source data as fallback 

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/pull/18791

### Release Date

19/1/2023

### Release Number

1.9.4

**Comment by danciaclara** [comment]
@dilippitchika @ashit-rath Do share the first draft for this update

**Comment by jnikhila** [comment]
cc: @somangshu

**Comment by dilippitchika** [comment]
Working on it

**Comment by dilippitchika** [comment]
Added the documentation, @jnikhila @danciaclara
