### ISSUE TITLE
[Docs]: Select Widget - Rehaul

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

N/A

### Documentation Link

https://docs.appsmith.com/reference/widgets/select

### Describe the problem and improvement.

Rehaul

**Comment by danciaclara** [comment]
# Select
    [Intro]

## Usage
      [Where select widget can be used]
      ### Filtering data 
      ### Form submission
       
## Properties
      [Properties Table]
    
## Events
       [Events Table]
       
## Displaying data
      [Intro]
      [Explain properties that help with displaying data]
### Options
### Default Selected Value

## Server-side filtering
     
## Further reading
## Troubleshooting

**Comment by danciaclara** [comment]
Related ticket - #602
