### ISSUE TITLE
[Docs]: Mention important notes before doing a manual update

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

na

### Documentation Link

https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl

### Describe the problem and improvement.

The Updates and Rollback information provided on https://docs.appsmith.com/getting-started/setup/instance-management/appsmithctl is not discoverable. We need to add cross-references whereever applicable. 

We need to explicitly callout the following 

- You should take a backup before you update.
- How to take a backup
- How to rollback to a previous update if you faced an issue

**Comment by jnikhila** [comment]
As discussed with @danciaclara - the severity is high.

**Comment by danciaclara** [comment]
Things to do.

- [ ] On every page that talks about updating Appsmith instance manually, cross reference to the sections that talk about backup and restore (also use the word rollback for in the content to improve discoverability). 
- [ ] appsmithctl should be written in lowercase in the sidebar and the title of the page, as that is a command line utility

**Comment by harshilp24** [comment]
@sum35h can we cross-reference to the same backup and restore link on all other deployments?

**Comment by sum35h** [comment]
@harshilp24  Yes, we can add that to everything except kubernetes/helm.
