### ISSUE TITLE
[Docs]: Add Server logs section for each platform

### ISSUE THREAD

**Issue by jnikhila** [appsmithorg/appsmith-docs#776]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

NA

### Release Date

NA

### Release Number

NA

### First Draft

NA

### Discord/slack/intercom Link if needed

https://theappsmith.slack.com/archives/C01CFTXD0N8/p1674542173357189

### Use cases or user requests

Add server logs for all the installations. Similar to[ docker logs](https://docs.appsmith.com/getting-started/setup/installation-guides/docker#docker-logs).

**Comment by jnikhila** [comment]
@danciaclara and @pranavkanade - Please add details if needed.

**Comment by jnikhila** [comment]
@sum35h / @pratapaprasanna - Could you please share the first draft for this?

**Comment by danciaclara** [comment]
Fixed by https://github.com/appsmithorg/appsmith-docs/pull/859
