### ISSUE TITLE
[Docs]: Add Geolocation

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#781]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

NA

### Documentation Link

https://docs.appsmith.com/reference/appsmith-framework/widget-actions

### Describe the problem and improvement.

Add docs for all the actions related to Geolocation. 
![geo_issue](https://user-images.githubusercontent.com/43263619/214503979-d746ac4a-82a9-4446-8c4b-a8f6615fa73b.PNG)

**Comment by danciaclara** [comment]
closed via https://github.com/appsmithorg/appsmith-docs/pull/1450

**Comment by danciaclara** [comment]
closed via https://github.com/appsmithorg/appsmith-docs/pull/1450

**Comment by bharath31** [comment]
canBeRequested `Boolean`
This property indicates the feasibility of accessing the user's current location. Use this to check if the user has granted location permissions and gracefully handle failures. eg: 
```
if(appsmith.geolocation.canBeRequested) { 
    // access the user's location
    appsmith.geolocation.getCurrentPosition()
}
else {
  // ask user to grant location access
  showAlert("Please allow location access on the browser and refresh this page")
}
```

------------------

currentPosition `object`
This object contains additional properties that can help determine the user's current position. 

refer: https://developer.mozilla.org/en-US/docs/Web/API/GeolocationCoordinates
https://developer.mozilla.org/en-US/docs/Web/API/GeolocationPosition

**Comment by rashmi-sahoo-git** [comment]
Docs are already available for the functions here:
- [geolocation.getCurrentPosition()](https://docs.appsmith.com/reference/appsmith-framework/context-object#geolocationgetcurrentposition) - Get Geolocation
- [geolocation.watchPosition()](https://docs.appsmith.com/reference/appsmith-framework/context-object#geolocationwatchposition) - Watch Geolocation
- [geolocation.clearWatch()](https://docs.appsmith.com/reference/appsmith-framework/context-object#geolocationclearwatch) - Stop watching Geolocation

Closing this ticket.
