### ISSUE TITLE
[Docs]: Add image to clarify cross-origin communication 

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

na

### Documentation Link

https://docs.appsmith.com/reference/appsmith-framework/widget-actions/post-message

### Describe the problem and improvement.

na

**Comment by spark-c** [comment]
PR: https://github.com/appsmithorg/appsmith-docs/pull/807
