### ISSUE TITLE
[Docs]: Document best practices for self-hosting and running Appsmith in production env

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

na

### Documentation Link

na

### Describe the problem and improvement.

There is no clear communication on how to setup Appsmith in a production environment. How should a user setup their instances and applications so that their management overhead is minimal? We should document this a lot better and add best practices

https://theappsmith.slack.com/archives/CNQ9Q91C0/p1674568962859169

**Comment by Pranay105** [comment]
Divided into 3 guides -
#1370 
#1371 
#1372

**Comment by Pranay105** [comment]
Divided into 3 guides -
#1370  
#1371 
#1372
