### ISSUE TITLE
[Docs]: Update doc for using Git to create multiple environments

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

na

### First Draft
https://github.com/appsmithorg/appsmith-docs/pull/946

### Documentation Link

https://docs.appsmith.com/learning-and-resources/how-to-guides/use-git-to-create-different-environments

### Describe the problem and improvement.

We have a how to guide to show users how to use git . 

The documentation is not clearly communicatng how to develop a CI/CD pipeline or create a workflow using multiple environments. The steps look more tailored on Git related terminology rather than environments.  We need to update this. Adding a video walkthrough for this would also be helpful

**Comment by jnikhila** [comment]
@infinitetrooper - Could you please help us [rewrite this doc](https://docs.appsmith.com/learning-and-resources/how-to-guides/use-git-to-create-different-environments) and share a first draft?

**Comment by infinitetrooper** [comment]
@jnikhila  - With the new multiple-environments feature coming up and solving the same problem, should we document this as a solution for managing multiple environments?

**Comment by jnikhila** [comment]
@infinitetrooper - the new multiple-environments feature is a Business Edition feature only. However, with this guide CE users can still benefit as the Community Edition also has Versioning with Git feature though for limited repos. We can enrich the document to help these users. Your thoughts?

**Comment by infinitetrooper** [comment]
Okay, yeah, makes sense but, we should use different terminology IMO. It's at best a workaround and we should also link the multiple environments docs to this page. Let me take a crack at updating this and we can discuss it. Gimme a few days.
