### ISSUE TITLE
[Docs]: Update steps for Docker and Kubernetes(BE)

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

na

### Describe the problem and improvement.

Certain installation process updates were made on the hidden pages, containing shorter versions of the intallation steps for BE users. PR - https://github.com/appsmithorg/appsmith-docs/pull/757

We need to update the pages on the docs to reflect these changes.

cc: @pranayagarwal96

**Comment by pranayagarwal96** [comment]
@sharat87 for context, as we are creating the new hidden pages to embed installation instructions on [customer.appsmith.com](https://release-customer.appsmith.com/), given there is a change in actual steps followed, we will also have to update the instructions on main docs pages as well (e.g. https://docs.appsmith.com/getting-started/setup/installation-guides/docker). Does that make sense?

**Comment by pranayagarwal96** [comment]
On all install and upgrade docs for BE, we should have first step as sign-up on [customer.appsmith.com](http://customer.appsmith.com/) and generate a trial license key. This is slightly important, since today we don't have any other place where we tell the user where to generate a trial license key
