### ISSUE TITLE
[Docs]: Update the AMI docs 

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Release Number or Date

N/A

### Documentation Link

https://docs.appsmith.com/getting-started/setup/installation-guides/aws-ami#step-4-deploy-appsmith-on-aws-cloud

### Discord/slack/intercom Link

https://theappsmith.slack.com/archives/C0341RERY4R/p1675885398601549

### Describe the problem and improvement.

A user is following our AWS AMI setup guide. Step 4.2 has them search for appsmith and then tells them to install, but we don’t explicitly give an image name or anything. 

Update the docs with correct ami and screenshot

**Comment by jnikhila** [comment]
Fixed as part of [#1279](https://github.com/appsmithorg/appsmith-docs/issues/1279)
