### ISSUE TITLE
How to change the color of Map widgets markers color?

### ISSUE THREAD

**Issue by codename89** [appsmithorg/appsmith-docs#830]
Hi! The expected structure is {lat: number, long: number, title?: string, color?: string}. What is the format of string for the color key? I have tried the hex code and its not working.

**Comment by danciaclara** [comment]
Hi @codename89 Apologies for the delay,  hex code works . See the screenshot below 
<img width="578" alt="Screenshot 2023-03-01 at 17 51 21" src="https://user-images.githubusercontent.com/32227135/222137997-749a06be-9b80-4120-a42e-ace857092210.png">
