### ISSUE TITLE
[Docs]: Custom Authentication Rehaul

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/advanced-concepts/how-to-implement-custom-authentication-on-appsmith

### Describe the problem and improvement.

Restructure and rewrite with better examples

**Comment by danciaclara** [comment]
Related #693

**Comment by spark-c** [comment]
Currently delayed to addition for section on refresh tokens
