### ISSUE TITLE
[Docs]: Update Display Data (read) page

### ISSUE THREAD

**Issue by harshilp24** [appsmithorg/appsmith-docs#880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets

### Discord/slack/intercom Link

N/A

### Describe the problem and improvement.

add this content to widget landing page

To access the values of an object with attribute names that contain spaces, use `obj["<ATTRIBUTE_NAME"]` instead of `obj.<ATTRIBUTE_NAME>`, where `"<ATTRIBUTE_NAME>"` is the placeholder for an attribute name. For example, if the attribute is `income tax`.

```javascript
 return { label: obj["income tax"], value: obj["income tax"]} 
 ```

**Comment by jnikhila** [comment]
@Pranay105 - Could you please also look into this while Rehauling the page? Please add your estimates too.

**Comment by Pranay105** [comment]
Sure.
