### ISSUE TITLE
[Docs]: Create a separate section for Business edition

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/upgrade-to-business-edition

### Describe the problem and improvement.

Today we have installation and upgrade of business editions in different places. they should be all accessible from one place.

**Comment by jnikhila** [comment]
The tab urls can also be implemented as part of this ticket for having different URLs for installation and upgrade instructions.
