### ISSUE TITLE
[Docs]: Displaying Data Rehaul

### ISSUE THREAD

**Issue by danciaclara** [appsmithorg/appsmith-docs#913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/data-access-and-binding/displaying-data-read

### Describe the problem and improvement.

Update content

**Comment by jnikhila** [comment]
@Pranay105 - Could you please add Sprint and estimates to the ticket?
