### ISSUE TITLE
[Docs]: AWS EC2

### ISSUE THREAD

**Issue by tomjose92** [appsmithorg/appsmith-docs#933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/getting-started/setup/installation-guides/aws-ecs

### Discord/slack/intercom Link

https://www.notion.so/appsmith/B-E-customer-onboarding-846630fd2ce246fba33918355dc285b8?pvs=4#b61e03cfba4446cab13a5705ea67b066

### Describe the problem and improvement.
**Need to have steps for deploying/upgrading the Business Edition of Appsmith on AWS EC2 instance**
We have started to get a fairly high number of customers who prefer to deploy Appsmith on an EC2 instance.
Our current deployment documentation for the same, does not have instructions to upgrade to the Business Edition.
So when the user is upgrading to or deploying a fresh build of Business Edition, they miss out on key steps like updating the image to appsmith-ee.

**Comment by jnikhila** [comment]
Thanks @tomjose92. @sharat87 / @sum35h - Could you please[ review the steps documented](https://www.notion.so/appsmith/B-E-customer-onboarding-846630fd2ce246fba33918355dc285b8?pvs=4#b61e03cfba4446cab13a5705ea67b066) for AWS EC2?

**Comment by jnikhila** [comment]
Closed [#1197](https://github.com/appsmithorg/appsmith-docs/pull/1197)
