### ISSUE TITLE
[Docs]: Augment internal properties for input widget

### ISSUE THREAD

**Issue by ramsaptami** [appsmithorg/appsmith-docs#934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/reference/widgets/input

### Describe the problem and improvement.

inputText and text have different uses depending on input type and parsed value usage by users. Refer to [this](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1677757204941789) slack thread for more information

**Comment by spark-c** [comment]
Closing this ticket, as it seems that `inputText` will be hidden from users again. Reference same thread linked in description
