### ISSUE TITLE
[Docs] Update the Docs on Custom Authentication

### ISSUE THREAD

**Issue by ame-appsmith** [appsmithorg/appsmith-docs#962]
Please update this documentation: https://docs.appsmith.com/advanced-concepts/how-to-implement-custom-authentication-on-appsmith
The test API for login is no longer valid: https://appsmith-tutorial-apis.herokuapp.com/auth/local
We either need to fix this endpoint or modify our docs.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_7xgr0)

**Comment by jnikhila** [comment]
@spark-c - Could you please validate and add comments for this?

**Comment by danciaclara** [comment]
Fixed by https://github.com/appsmithorg/appsmith-docs/pull/897
