### ISSUE TITLE
[Docs]: JS Objects documentation links to a closed Git issue

### ISSUE THREAD

**Issue by eedwardsSGS** [appsmithorg/appsmith-docs#969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Documentation Link

https://docs.appsmith.com/core-concepts/writing-code/javascript-editor-beta

### Describe the problem and improvement.

Documentation says "At the moment, you can't use JS Objects across pages. You can subscribe to[ the issue](https://github.com/appsmithorg/appsmith/issues/1751) and follow the progress." but that issue is already closed and is about the JS Editor as a whole, not just accessing across pages.

Please update to point to the issue for the making JS Objects accessible across pages.

**Comment by AnsonCode** [comment]
Hope support that across page use JS Objects.
