### ISSUE TITLE
[Docs]: Add documentation for AWS Cognito SSO setup

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem and improvement.

This documentation currently doesn't exist. AWS Cognito is a well-used IDP and we should provide documentation as it's a tricky config. We need to do this for OIDC, SAML, User pools, and Federated Identity

The steps are written by Raksha [here](https://docs.google.com/document/d/1V46L8oLWu5D3aaU30DmR5gwT7A4JlSvqLtBJXn3VjAU/edit?usp=sharing). We can follow the current structure and modify that for Cognito. I can work with the assigned person to review and unblock where required.

**Comment by jnikhila** [comment]
[Duplicate](https://app.zenhub.com/workspaces/user-education-pod-61c01739f309a80011b48267/issues/gh/appsmithorg/appsmith/15827)
