### ISSUE TITLE
[Docs]: Local Database or API page rehaul

### ISSUE THREAD

**Issue by spark-c** [appsmithorg/appsmith-docs#975]
Rehaul of ["Connect via Localhost"](https://docs.appsmith.com/advanced-concepts/more/how-to-work-with-local-apis-on-appsmith) page.

**Comment by jnikhila** [comment]
Please cater to this feedback while rehauling the doc: 
> Documentation has some gaps. Needed ngrok to connect to the backend. Both nginx local and docker local didn’t work and reason was evident after a bit of thinking since requests were sent into a docker env. Explicit mention of steps can be added if the developer wants to run the setup end to end locally.
