### ISSUE TITLE
[Docs]: Update Google OAuth config process to include URL copy-paste changes

### ISSUE THREAD

**Issue by infinitetrooper** [appsmithorg/appsmith-docs#984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Engineering Ticket Link

https://github.com/appsmithorg/appsmith/issues/21170

### Release Date

26/03/23

### Release Number

v1.9.13

**Comment by danciaclara** [comment]
fixed by https://github.com/appsmithorg/appsmith-docs/pull/973
